{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common-ktx",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-ktx-1.5.1.aar",
          "url": "media3-common-ktx-1.5.1.aar",
          "size": 11850,
          "sha512": "1e4fbad2fccea433509474d970bbda0d4506a6f9a1adcb4c729d746d745be191095647bc270c70ac2aca25e802c3bdca3145c6089c77feab90b5380a7f3ae92e",
          "sha256": "21b64a192651e52c629c1a50725e971b340166849b03520708bd9a263ea6ef8c",
          "sha1": "8c9ea0cc9172fd2b229c81bc112a4874d11fdd95",
          "md5": "1e261c7ef2b9aa6fab1eef59338ccaf9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-ktx-1.5.1.aar",
          "url": "media3-common-ktx-1.5.1.aar",
          "size": 11850,
          "sha512": "1e4fbad2fccea433509474d970bbda0d4506a6f9a1adcb4c729d746d745be191095647bc270c70ac2aca25e802c3bdca3145c6089c77feab90b5380a7f3ae92e",
          "sha256": "21b64a192651e52c629c1a50725e971b340166849b03520708bd9a263ea6ef8c",
          "sha1": "8c9ea0cc9172fd2b229c81bc112a4874d11fdd95",
          "md5": "1e261c7ef2b9aa6fab1eef59338ccaf9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-ktx-1.5.1-sources.jar",
          "url": "media3-common-ktx-1.5.1-sources.jar",
          "size": 2656,
          "sha512": "172e4c6362e430ee526ba1172349504d98d0e205b251de49cca45aad7867a61fefc285e9af2d2343a3dfd0e0e6f11aa4780cba9a328df5d851f2f194d77b3974",
          "sha256": "652abd7be760c3504bafabf5c475cfcdfdf5e66eb4730de2fd652034b34fe31f",
          "sha1": "d707452d222fe06d37e5aced0b58ea34f488dc9c",
          "md5": "af04e3097eafa1b777148023e0cf14e2"
        }
      ]
    }
  ]
}
