{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.9.0.aar",
          "url": "media3-cast-1.9.0.aar",
          "size": 97702,
          "sha512": "7d1854be104548d9513d1e630f45eea99896404250ba07e35d5cc323fff58d719631e1fe8c10b116906e54f348873fa62f9cc67bd273863adb6fd2536b3442d9",
          "sha256": "08569f77d5d38cf6b761bc319a97e139f23c24947e433047a360dacbfe5df056",
          "sha1": "5889fdbf2d2df2a9895cd55db7029c8484750688",
          "md5": "bd9dac11703931a4865a4c5bd1ee13d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.9.0.aar",
          "url": "media3-cast-1.9.0.aar",
          "size": 97702,
          "sha512": "7d1854be104548d9513d1e630f45eea99896404250ba07e35d5cc323fff58d719631e1fe8c10b116906e54f348873fa62f9cc67bd273863adb6fd2536b3442d9",
          "sha256": "08569f77d5d38cf6b761bc319a97e139f23c24947e433047a360dacbfe5df056",
          "sha1": "5889fdbf2d2df2a9895cd55db7029c8484750688",
          "md5": "bd9dac11703931a4865a4c5bd1ee13d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.9.0-sources.jar",
          "url": "media3-cast-1.9.0-sources.jar",
          "size": 42891,
          "sha512": "0aa005c5b14752bdf2d7c01e4ba32311fddf5fa5fd029999e3fc51e1472b427c4917f0eca5199a1099ca05b4fcdfc8caa1e897a2baa07a3f6638f57487d0cb6a",
          "sha256": "95c3cbbf1ef21970ffea76821e347a11f5e258adeeef0684160de2e5ed06a479",
          "sha1": "4bf8e25b494409056f4ff06d6c1dafa12303b933",
          "md5": "876125447020d8cbc39083e7784496b2"
        }
      ]
    }
  ]
}
