{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-iamf",
    "version": "1.11.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0-rc01.aar",
          "url": "media3-decoder-iamf-1.11.0-rc01.aar",
          "size": 11926950,
          "sha512": "62bb3de6619070fe85cef12b02fa21e47be2a6f85c1c2ff953f6fa0010b3916df1296d7c8d7c443bf083391208af5fb7c856a09a28d2957f2b8e37b26da5bdaa",
          "sha256": "443a33b12439245bf560ec80d1cf65aa78525e201f44fb2f98b5d57bb52c33c1",
          "sha1": "456b61bd500a80bed51521d7d1a514f1f4c8be44",
          "md5": "ae248d7900cc5519c3e2186ca0a2e71b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0-rc01.aar",
          "url": "media3-decoder-iamf-1.11.0-rc01.aar",
          "size": 11926950,
          "sha512": "62bb3de6619070fe85cef12b02fa21e47be2a6f85c1c2ff953f6fa0010b3916df1296d7c8d7c443bf083391208af5fb7c856a09a28d2957f2b8e37b26da5bdaa",
          "sha256": "443a33b12439245bf560ec80d1cf65aa78525e201f44fb2f98b5d57bb52c33c1",
          "sha1": "456b61bd500a80bed51521d7d1a514f1f4c8be44",
          "md5": "ae248d7900cc5519c3e2186ca0a2e71b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0-rc01-sources.jar",
          "url": "media3-decoder-iamf-1.11.0-rc01-sources.jar",
          "size": 10758,
          "sha512": "bf4053afe46ac7845d77d22320a36467b52c662399257f8915f20e94cebd8349897d14ce5e04e56107c0238f046d01d2fcf418185ea6ead35c5e6598024a9cd4",
          "sha256": "cf31c3a765727b532bc2c39a2a0cc76f41c97cef233e220cddef602071d5c269",
          "sha1": "4771b9824ec8370593991b2405539d2cb669df8d",
          "md5": "309a4e033b9bc384fab0cc46f3364800"
        }
      ]
    }
  ]
}
