{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-effect",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.9.0.aar",
          "url": "media3-effect-1.9.0.aar",
          "size": 321449,
          "sha512": "1834ffc57b0b2c681dfc46aa2617a30763f9bd3a02a5b39491f783ca8b9b23f74fba9f90d801256b0a7e458945f4e3f2d8d2151e4559819d3936354a35d5cc8c",
          "sha256": "f6029884e6aa225cdb10bc665c67114dbbcb54d4d740f8040106f75ef7c64b2e",
          "sha1": "639302783aa11ec849d8e042d1bf74c2df14057d",
          "md5": "7e9cea7ebd203bd985030564b52d01d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.9.0.aar",
          "url": "media3-effect-1.9.0.aar",
          "size": 321449,
          "sha512": "1834ffc57b0b2c681dfc46aa2617a30763f9bd3a02a5b39491f783ca8b9b23f74fba9f90d801256b0a7e458945f4e3f2d8d2151e4559819d3936354a35d5cc8c",
          "sha256": "f6029884e6aa225cdb10bc665c67114dbbcb54d4d740f8040106f75ef7c64b2e",
          "sha1": "639302783aa11ec849d8e042d1bf74c2df14057d",
          "md5": "7e9cea7ebd203bd985030564b52d01d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-effect-1.9.0-sources.jar",
          "url": "media3-effect-1.9.0-sources.jar",
          "size": 218085,
          "sha512": "e086013be39279635cdc541ba0049d2f8f234e2f32d1ffc6885d7820fa553f609a4d22aaf7cf99c92ae8dec72994c00a0c35a43ce20da304ddb5490ae764efec",
          "sha256": "f0e9bb21e849721ed7bd2c1a80f0daf2c3ad93b02be373f293c2efbd14dc6389",
          "sha1": "606c94140d7afd4575d170db996197aa34b9804b",
          "md5": "f4d1a4534b03e53d4fb852a98672471b"
        }
      ]
    }
  ]
}
