{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.3.0.aar",
          "url": "media3-exoplayer-1.3.0.aar",
          "size": 1395759,
          "sha512": "3994551cc431dfba8f25e1dea2f35327198c4126db54d781d95a59f0e1a9c4d45dfc46ed120f0345629673cd27d359407c66df6712932032bd7910867f23e0b2",
          "sha256": "68b96cea88fca07141db6d126e4c182b424be6a650571e4c52d8de1d01b4f3e8",
          "sha1": "b32aed2156d817d775c2b79005ffddba58141e1d",
          "md5": "b14c8df167f3a8714f9282029cfbb23f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.3.0.aar",
          "url": "media3-exoplayer-1.3.0.aar",
          "size": 1395759,
          "sha512": "3994551cc431dfba8f25e1dea2f35327198c4126db54d781d95a59f0e1a9c4d45dfc46ed120f0345629673cd27d359407c66df6712932032bd7910867f23e0b2",
          "sha256": "68b96cea88fca07141db6d126e4c182b424be6a650571e4c52d8de1d01b4f3e8",
          "sha1": "b32aed2156d817d775c2b79005ffddba58141e1d",
          "md5": "b14c8df167f3a8714f9282029cfbb23f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.3.0-sources.jar",
          "url": "media3-exoplayer-1.3.0-sources.jar",
          "size": 1017319,
          "sha512": "e9dbc8c149d5fc33ae02da16b2ac9b03b459584b17c56eeb0d609481b331c8381bec89b68935e3b567187142119ce30d2d200a39534f0c20920c71d8d2690a01",
          "sha256": "e9119278872e860e7a9642a5b08380ab6a4a7d3c458854216930c53e4b45f067",
          "sha1": "d24a574f5fa49a2c694585eeadf5f7cff1d8df8a",
          "md5": "9630fa964a39c5cb0b7326d53d832f05"
        }
      ]
    }
  ]
}
