{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-ima",
    "version": "1.10.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.39.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.10.0-rc02.aar",
          "url": "media3-exoplayer-ima-1.10.0-rc02.aar",
          "size": 92872,
          "sha512": "0a5007922484c74b4fdff5d78ccf8ea2cdc2e3bb7aa6b0a334714a461a59f484d5dde5e4b7e54d9c5f0cdafa805bccc56a922c8694b90698ee90729340b652c2",
          "sha256": "37db296ad20ee30e191200d9153e9c1b4b1571caa9289b13d447196d583e6ece",
          "sha1": "aabc2e73a2c9ef133e39c6ff19f768e68cbcd637",
          "md5": "f743b21189af26fe69c19a51fa03b132"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.39.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.10.0-rc02.aar",
          "url": "media3-exoplayer-ima-1.10.0-rc02.aar",
          "size": 92872,
          "sha512": "0a5007922484c74b4fdff5d78ccf8ea2cdc2e3bb7aa6b0a334714a461a59f484d5dde5e4b7e54d9c5f0cdafa805bccc56a922c8694b90698ee90729340b652c2",
          "sha256": "37db296ad20ee30e191200d9153e9c1b4b1571caa9289b13d447196d583e6ece",
          "sha1": "aabc2e73a2c9ef133e39c6ff19f768e68cbcd637",
          "md5": "f743b21189af26fe69c19a51fa03b132"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-ima-1.10.0-rc02-sources.jar",
          "url": "media3-exoplayer-ima-1.10.0-rc02-sources.jar",
          "size": 53510,
          "sha512": "5049206bc794a878c056e8203dd9cf7bdbac42d39bcd7229d634c895a8f61f0ac6c6e4ec3fbc5b30709a2188108fe07f32fc4bbe14c2f0215ffd47eeb6a73039",
          "sha256": "98e53d3114f75baa2c0e38baaba05eac0426e72e41de32a0f179a827722d87f0",
          "sha1": "016e423915b356903884efd3aa5e4908b9b7ab64",
          "md5": "7a8d26b959b80389939688dc3a7b1137"
        }
      ]
    }
  ]
}
