{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-database",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-database-1.9.0.aar",
          "url": "media3-database-1.9.0.aar",
          "size": 7197,
          "sha512": "38e9ea8ecf2199d5bc95f7a31ebe747be61815044466c42afb7aa63756c80315933e1758a07696fd5508bebea1ee35aefa28142b3e3cc4611535f599c27cdfa9",
          "sha256": "de88a2ca8fd1efb1dbe7d8cd4c728fca15fafb629442514a689dea1788817637",
          "sha1": "e0511bf4044fc64832605682e9cfddbf23f6c155",
          "md5": "66cb984da89ddd4c9d7563ca050db42f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-database-1.9.0.aar",
          "url": "media3-database-1.9.0.aar",
          "size": 7197,
          "sha512": "38e9ea8ecf2199d5bc95f7a31ebe747be61815044466c42afb7aa63756c80315933e1758a07696fd5508bebea1ee35aefa28142b3e3cc4611535f599c27cdfa9",
          "sha256": "de88a2ca8fd1efb1dbe7d8cd4c728fca15fafb629442514a689dea1788817637",
          "sha1": "e0511bf4044fc64832605682e9cfddbf23f6c155",
          "md5": "66cb984da89ddd4c9d7563ca050db42f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-database-1.9.0-sources.jar",
          "url": "media3-database-1.9.0-sources.jar",
          "size": 8391,
          "sha512": "5de040766ed9bdddf3e551b903f49c09c2bfecb2330c9e78a249b9d86f1cef5cba5582a9f10098f72c7adf7e786d6fdd1154521f74dc8a35d3a528c03aab7086",
          "sha256": "1baca4ff0a32e76d08b92ed5d33e0278aa34a9e9c537edbc2fd39573e8ec46a3",
          "sha1": "b8a91c32c00129b65c8cc9148201632b27c4a240",
          "md5": "b509a427e0eee1b73f1710b698bdcd9e"
        }
      ]
    }
  ]
}
