{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.8.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.8.0-rc01.aar",
          "url": "media3-decode-opus-1.8.0-rc01.aar",
          "size": 511553,
          "sha512": "19ef9ca11fb781fadbba8ba7d19dc42a44f17f0dd0a11f66513007ccc9bb2d72afd634db3958433bbd5a416a200790c20e908cfebc9a78ba0d38e34e5067a515",
          "sha256": "6455595dcdc907a312d9b320e7a6a395bc4136554f030f41e761de7e39dd1f75",
          "sha1": "ef0ffa68e22a39d8b2031436dce9ca1385282b4d",
          "md5": "140d77b8cecf47a7ba1d70b0c7e27f02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.8.0-rc01.aar",
          "url": "media3-decode-opus-1.8.0-rc01.aar",
          "size": 511553,
          "sha512": "19ef9ca11fb781fadbba8ba7d19dc42a44f17f0dd0a11f66513007ccc9bb2d72afd634db3958433bbd5a416a200790c20e908cfebc9a78ba0d38e34e5067a515",
          "sha256": "6455595dcdc907a312d9b320e7a6a395bc4136554f030f41e761de7e39dd1f75",
          "sha1": "ef0ffa68e22a39d8b2031436dce9ca1385282b4d",
          "md5": "140d77b8cecf47a7ba1d70b0c7e27f02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.8.0-rc01-sources.jar",
          "url": "media3-decode-opus-1.8.0-rc01-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
