{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-container",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.4.0.aar",
          "url": "media3-container-1.4.0.aar",
          "size": 24985,
          "sha512": "2527c85b7e6dce94662ef116ba285990e52633ca4859cec7219e318361eb3bc91edb25483e8e899d00e26c0f646d5df54104cab3a83956a731cc808972c9c286",
          "sha256": "65b6d22c96dfb5ce76754b08f5b004ee0dbdbe60793c5eab9f95c1f54f95f4b0",
          "sha1": "a475312c1b14def1d8c3b9e82bc605b79e434803",
          "md5": "3973cc91bedaa3b0fe4f161b110d8285"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.4.0.aar",
          "url": "media3-container-1.4.0.aar",
          "size": 24985,
          "sha512": "2527c85b7e6dce94662ef116ba285990e52633ca4859cec7219e318361eb3bc91edb25483e8e899d00e26c0f646d5df54104cab3a83956a731cc808972c9c286",
          "sha256": "65b6d22c96dfb5ce76754b08f5b004ee0dbdbe60793c5eab9f95c1f54f95f4b0",
          "sha1": "a475312c1b14def1d8c3b9e82bc605b79e434803",
          "md5": "3973cc91bedaa3b0fe4f161b110d8285"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-container-1.4.0-sources.jar",
          "url": "media3-container-1.4.0-sources.jar",
          "size": 19928,
          "sha512": "f3ec4b28c1a7e6fe018116fed013d9829a3039b3a6b1bcb7fbf9fd61e53c93afbe24a3c678d73635c497b285f6f31ba3069214a82b8c97a4882aac9f6c1322cf",
          "sha256": "8512bb2e8f8f3ffb4efbd00ccd326da951dc5f3407cba025cd9842c8158b68ad",
          "sha1": "6f6e15048100ea61a392601e40a8d5b6af262f36",
          "md5": "fa53ed9c1517bf476eca34c9178ee0d8"
        }
      ]
    }
  ]
}
