{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui-leanback",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-leanback-1.10.0.aar",
          "url": "media3-ui-leanback-1.10.0.aar",
          "size": 6734,
          "sha512": "0975daf86a7d79a090f14f4e494266f41a77f1c8ccd8d29508fea3f3d5b9a84937887eb795fe6e9e3aac514b0ebf8e5ee68392fc6803b09a32492c31e6526fe6",
          "sha256": "4e0943996829f4f923f59533b8755ea3a59bc6b269245e866cd2aeb2c8c226f7",
          "sha1": "fa0e35469c6338dbd9dee8d60701d49e82347d56",
          "md5": "b5a607850a3d915db3a9d935ec9d6d7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-leanback-1.10.0.aar",
          "url": "media3-ui-leanback-1.10.0.aar",
          "size": 6734,
          "sha512": "0975daf86a7d79a090f14f4e494266f41a77f1c8ccd8d29508fea3f3d5b9a84937887eb795fe6e9e3aac514b0ebf8e5ee68392fc6803b09a32492c31e6526fe6",
          "sha256": "4e0943996829f4f923f59533b8755ea3a59bc6b269245e866cd2aeb2c8c226f7",
          "sha1": "fa0e35469c6338dbd9dee8d60701d49e82347d56",
          "md5": "b5a607850a3d915db3a9d935ec9d6d7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-leanback-1.10.0-sources.jar",
          "url": "media3-ui-leanback-1.10.0-sources.jar",
          "size": 4407,
          "sha512": "20a816c372ac5e7835dbf83737469ea30354dd6b21d38d7164482fdbab04c9dbfa979ae2d9273f2c5449d39c331eb29e564a0d9226f660a9c17f6e12920f71b0",
          "sha256": "b48620ff7de85c0a7998d584cc30c0a365a5d94f218bc91c4f3f82db1c246276",
          "sha1": "8dd5e7d7535bc7ed58d9c8c102f5ca83e104e91f",
          "md5": "0861a5a93f2eb1dc600500acfe88e220"
        }
      ]
    }
  ]
}
