{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui-compose-material3",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-material3-1.10.0-alpha01.aar",
          "url": "media3-ui-compose-material3-1.10.0-alpha01.aar",
          "size": 237451,
          "sha512": "6b6523fb23aebbc0e3e43226a8101a57976184051f11926f33fbe26db2e0304e0b7c0b7cededab22f3e028b7e25516d9a85a870c25daa8779ced27a399235e6a",
          "sha256": "a6fe79bb9c2dd4288c82e65b185f8d82ccd21e67ebc37500d0e16e5badd3ab14",
          "sha1": "426867a4875c04f581ea5f49b3a78fea1b3338a9",
          "md5": "4fd2f282783407f41dae8f102b82016b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-material3-1.10.0-alpha01.aar",
          "url": "media3-ui-compose-material3-1.10.0-alpha01.aar",
          "size": 237451,
          "sha512": "6b6523fb23aebbc0e3e43226a8101a57976184051f11926f33fbe26db2e0304e0b7c0b7cededab22f3e028b7e25516d9a85a870c25daa8779ced27a399235e6a",
          "sha256": "a6fe79bb9c2dd4288c82e65b185f8d82ccd21e67ebc37500d0e16e5badd3ab14",
          "sha1": "426867a4875c04f581ea5f49b3a78fea1b3338a9",
          "md5": "4fd2f282783407f41dae8f102b82016b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-compose-material3-1.10.0-alpha01-sources.jar",
          "url": "media3-ui-compose-material3-1.10.0-alpha01-sources.jar",
          "size": 22582,
          "sha512": "3822617b5556838b921a33d9ccac4ffec1e38435a4d4d1f1c9044a67bdb2ce7d330f0d2bd3925466e2f91c01a3438e4887f8def1ebc6e474c246cd1bfeaab388",
          "sha256": "b5a7d4e4a190fcfee51b9fe65f23c1d97453251f9a87aaaed24b9056b902ea1f",
          "sha1": "273f56fd0e341c696d2f365f6afde9c2014ef8fa",
          "md5": "97155c06c377288fcfc6944c8beef59c"
        }
      ]
    }
  ]
}
