{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-dash",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.3.1.aar",
          "url": "media3-exoplayer-dash-1.3.1.aar",
          "size": 139535,
          "sha512": "17c9e89e2c926e896738b36c6a780136e7ed09c583cbbef450e2da753eec95ea71c662d9854d2b7968def7a398c61a14f813d8a2ff7b54f1f466419396815dd3",
          "sha256": "c1d8f825e18d3d2c30abb46ab1dfd43dee9a41d36c2a7e9bc169eb93b221db58",
          "sha1": "8ea310ff890486173279f0d6f8dd2d635a9375cb",
          "md5": "016d7c8dd798a991a1690010d157aea4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-dash-1.3.1.aar",
          "url": "media3-exoplayer-dash-1.3.1.aar",
          "size": 139535,
          "sha512": "17c9e89e2c926e896738b36c6a780136e7ed09c583cbbef450e2da753eec95ea71c662d9854d2b7968def7a398c61a14f813d8a2ff7b54f1f466419396815dd3",
          "sha256": "c1d8f825e18d3d2c30abb46ab1dfd43dee9a41d36c2a7e9bc169eb93b221db58",
          "sha1": "8ea310ff890486173279f0d6f8dd2d635a9375cb",
          "md5": "016d7c8dd798a991a1690010d157aea4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.3.1-sources.jar",
          "url": "media3-exoplayer-dash-1.3.1-sources.jar",
          "size": 94072,
          "sha512": "4a8cc04296a562a24a9bf8684613eb701500fd42c9ac01614768ab6b45bc39cb69c51aa2aa6bcf9ca5fe2b8b355754dceb8b7036144d3ab19f143c767c8c763e",
          "sha256": "20200245b8edbad44d6b960dac715051385fc0e8beafaac9a213401cb9dc48c1",
          "sha1": "31eb85e269f8e024c654e8ed1c9184bd85e2cf2c",
          "md5": "7111afb554ffb7819a5efc12e7bba733"
        }
      ]
    }
  ]
}
