{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.9.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.9.0-rc01.aar",
          "url": "media3-cast-1.9.0-rc01.aar",
          "size": 97705,
          "sha512": "556ccec8738abf084a67c7d5cd91475465515b5dece177fb804feff10c82b617e979191c7739fb0417f1ab52f282ff2c78351fd3426bb7f1eb68c5d670141c37",
          "sha256": "f330795218f81195e3def7c5e99a0d25857799c380e53e49daf5bac6d5fc263f",
          "sha1": "7a692462d813c170a7b56f64061cdbd67fcd6dfe",
          "md5": "6f2528bc40da7002f3f044c4c0ad16b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.9.0-rc01.aar",
          "url": "media3-cast-1.9.0-rc01.aar",
          "size": 97705,
          "sha512": "556ccec8738abf084a67c7d5cd91475465515b5dece177fb804feff10c82b617e979191c7739fb0417f1ab52f282ff2c78351fd3426bb7f1eb68c5d670141c37",
          "sha256": "f330795218f81195e3def7c5e99a0d25857799c380e53e49daf5bac6d5fc263f",
          "sha1": "7a692462d813c170a7b56f64061cdbd67fcd6dfe",
          "md5": "6f2528bc40da7002f3f044c4c0ad16b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.9.0-rc01-sources.jar",
          "url": "media3-cast-1.9.0-rc01-sources.jar",
          "size": 42891,
          "sha512": "0aa005c5b14752bdf2d7c01e4ba32311fddf5fa5fd029999e3fc51e1472b427c4917f0eca5199a1099ca05b4fcdfc8caa1e897a2baa07a3f6638f57487d0cb6a",
          "sha256": "95c3cbbf1ef21970ffea76821e347a11f5e258adeeef0684160de2e5ed06a479",
          "sha1": "4bf8e25b494409056f4ff06d6c1dafa12303b933",
          "md5": "876125447020d8cbc39083e7784496b2"
        }
      ]
    }
  ]
}
