{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-av1",
    "version": "1.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-alpha01.aar",
          "url": "media3-decoder-av1-1.11.0-alpha01.aar",
          "size": 2291488,
          "sha512": "6886a84f2b98066b55d9a2032ad79552c6500a5d3897f291031b90323f19565d738ae495982e19fe9cb4f4678255d735960645c5012ad060f5448b09340063f6",
          "sha256": "57fdb6833f13efa78af57a98202bb1688b8106937e3a87eb2a1997b7e0418b08",
          "sha1": "011c12e089047c01c0147f07f729ea33d353ab90",
          "md5": "cc2c0a0d532cf911254a9998e731435f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-alpha01.aar",
          "url": "media3-decoder-av1-1.11.0-alpha01.aar",
          "size": 2291488,
          "sha512": "6886a84f2b98066b55d9a2032ad79552c6500a5d3897f291031b90323f19565d738ae495982e19fe9cb4f4678255d735960645c5012ad060f5448b09340063f6",
          "sha256": "57fdb6833f13efa78af57a98202bb1688b8106937e3a87eb2a1997b7e0418b08",
          "sha1": "011c12e089047c01c0147f07f729ea33d353ab90",
          "md5": "cc2c0a0d532cf911254a9998e731435f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-alpha01-sources.jar",
          "url": "media3-decoder-av1-1.11.0-alpha01-sources.jar",
          "size": 11543,
          "sha512": "f6885d2a7c0c88a9dcedd2dc276f9d5a19a5783237b69f6980f8d5b00b046cfa10c8d3db9961536d62581c2ce38935b9d4dec38f4b71f32c4436f6d98be12cd7",
          "sha256": "332832813bd15ebde22ca951a5dbbffd7dc6e9c3ed1cdc60f58f7cb7dc4596e3",
          "sha1": "27fbcdc7214fa6d87fc64e24f1d581040d209b17",
          "md5": "0e46ed2c1f5449ab0becff6c2cdf38a1"
        }
      ]
    }
  ]
}
