{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.10.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.10.0-beta01.aar",
          "url": "media3-ui-1.10.0-beta01.aar",
          "size": 433095,
          "sha512": "0c08f5fabbdd7a0948de39b8aa731fe4fa41beba74f53126f1249a48a81353b3e9031839122a0ed0247d8ed6db8b9c59dab421ebdee198894e69e689df02ea8e",
          "sha256": "9b314b9acc3859e2108ddfbbf94aacf4be0022507571e6b4a8c57f26dda8713d",
          "sha1": "ff0663d234331781d0847b0d6b031f1c3759fbc5",
          "md5": "4c7d1553bad424a1ac93ac9d88cba2ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.10.0-beta01.aar",
          "url": "media3-ui-1.10.0-beta01.aar",
          "size": 433095,
          "sha512": "0c08f5fabbdd7a0948de39b8aa731fe4fa41beba74f53126f1249a48a81353b3e9031839122a0ed0247d8ed6db8b9c59dab421ebdee198894e69e689df02ea8e",
          "sha256": "9b314b9acc3859e2108ddfbbf94aacf4be0022507571e6b4a8c57f26dda8713d",
          "sha1": "ff0663d234331781d0847b0d6b031f1c3759fbc5",
          "md5": "4c7d1553bad424a1ac93ac9d88cba2ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.10.0-beta01-sources.jar",
          "url": "media3-ui-1.10.0-beta01-sources.jar",
          "size": 120052,
          "sha512": "02b1712ba1d3fe872f3a3a1611ea2a65f84b66f750e72eaef384696156b5b3d6a2016e80e80c246df56d25d8148a89dfd18a030135fae7be0ddb8f6da71dddf6",
          "sha256": "2abea5e2d78f123206a552d99fffd93a54a5c923d78c42416cc5d1d69193c901",
          "sha1": "f6e4bba9c145fdacb0bb8a449681e7cf19d5f457",
          "md5": "615e83887882e958b32a1121db956d91"
        }
      ]
    }
  ]
}
