{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-test-utils-robolectric",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-test-utils-robolectric-1.3.1.aar",
          "url": "media3-test-utils-robolectric-1.3.1.aar",
          "size": 26148,
          "sha512": "a2124e7c367e72742c4e1d2783cb74ebb9779c4c63f73622e421364aedd7f85b75055e78f40055c6e9697ced1e4f90f7f62b680c43b13b6b02e6d7f6f5b03e28",
          "sha256": "2703c91071c60c72f38822acb63a4f3b74a80cf1996e5e052cb6ee4c2f88174c",
          "sha1": "a4ea2ab8fed523798b3afc36e7c448cdf516e8c6",
          "md5": "5f99b146c2cffe6cbc803c26b0832ea3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-robolectric-1.3.1.aar",
          "url": "media3-test-utils-robolectric-1.3.1.aar",
          "size": 26148,
          "sha512": "a2124e7c367e72742c4e1d2783cb74ebb9779c4c63f73622e421364aedd7f85b75055e78f40055c6e9697ced1e4f90f7f62b680c43b13b6b02e6d7f6f5b03e28",
          "sha256": "2703c91071c60c72f38822acb63a4f3b74a80cf1996e5e052cb6ee4c2f88174c",
          "sha1": "a4ea2ab8fed523798b3afc36e7c448cdf516e8c6",
          "md5": "5f99b146c2cffe6cbc803c26b0832ea3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-test-utils-robolectric-1.3.1-sources.jar",
          "url": "media3-test-utils-robolectric-1.3.1-sources.jar",
          "size": 16143,
          "sha512": "28dc8313b8f86f4a1b3d4f5e173986d7cd8c2c216551c327c077b5787b3d12690566a4755265be0680896fb884a0c580ab41c25108190e51e0dd5dcb76b1bbd4",
          "sha256": "e16239d19b30bf0656b940df6bfbeca4e8076638a8a2fd4da1e32e0695455b66",
          "sha1": "0aefbb27dc83466f1cdb8d0b861000de2d778629",
          "md5": "b3e63e3b4c684680c5f4ba5d4f571b9d"
        }
      ]
    }
  ]
}
