{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.8.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.8.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.8.0-rc02.aar",
          "url": "media3-exoplayer-1.8.0-rc02.aar",
          "size": 1578273,
          "sha512": "d11e478adce3192b044d7ef9f9e4d57f6a13ee4a766e6b32ea0a40a18f21cdc6fe480483de30e5822d992dec25b980abaf5ff270c2c11804076a836ac8698173",
          "sha256": "ce6ea7a85f6cf0283393194a3d7ee012ea772ba95c8bede2289a9f0d1a5ad61b",
          "sha1": "22df4af46b0a018b75a2567d9d2dd862f2cef9d9",
          "md5": "7a858f5dcbc6ed9721b686aa855b3f57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.8.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.8.0-rc02.aar",
          "url": "media3-exoplayer-1.8.0-rc02.aar",
          "size": 1578273,
          "sha512": "d11e478adce3192b044d7ef9f9e4d57f6a13ee4a766e6b32ea0a40a18f21cdc6fe480483de30e5822d992dec25b980abaf5ff270c2c11804076a836ac8698173",
          "sha256": "ce6ea7a85f6cf0283393194a3d7ee012ea772ba95c8bede2289a9f0d1a5ad61b",
          "sha1": "22df4af46b0a018b75a2567d9d2dd862f2cef9d9",
          "md5": "7a858f5dcbc6ed9721b686aa855b3f57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.8.0-rc02-sources.jar",
          "url": "media3-exoplayer-1.8.0-rc02-sources.jar",
          "size": 1135602,
          "sha512": "7423b43a309bdb1fcc790014874948045b600fd16234d156a122c6ba86b34fb4360c01702d7a1cd790aeb6b7c4eb036388366fabb9b1f8d0fd3468666d85957f",
          "sha256": "4524d75e1daa680e07cb0e3fe2a21174b2a9c69ab194dd30d2be8e63b3d063d9",
          "sha1": "1a572b3fb8b4f47c88f732224a7fa3d8554f412d",
          "md5": "8003f6fd9b21af2944297d1d4a62be52"
        }
      ]
    }
  ]
}
