{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.0-alpha01.aar",
          "url": "media3-datasource-1.11.0-alpha01.aar",
          "size": 168431,
          "sha512": "9721e87c4201f7a277825343599aed851cf5edd50324b3c55389d6e27ad3271a8e024df6d221aaabaf3eccde912565ef1eb4b248b074b26176a7cdd2ea44870b",
          "sha256": "f1a610f506c0f1dc4d72b9b5c61b4208293418de6e3bcc56b2d58a0c9341abb0",
          "sha1": "59aee8ac095e87e501937d1ee545a6ec74ddd06c",
          "md5": "8fd7a7c386cd76fc3375a3d065f1b22f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.0-alpha01.aar",
          "url": "media3-datasource-1.11.0-alpha01.aar",
          "size": 168431,
          "sha512": "9721e87c4201f7a277825343599aed851cf5edd50324b3c55389d6e27ad3271a8e024df6d221aaabaf3eccde912565ef1eb4b248b074b26176a7cdd2ea44870b",
          "sha256": "f1a610f506c0f1dc4d72b9b5c61b4208293418de6e3bcc56b2d58a0c9341abb0",
          "sha1": "59aee8ac095e87e501937d1ee545a6ec74ddd06c",
          "md5": "8fd7a7c386cd76fc3375a3d065f1b22f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.11.0-alpha01-sources.jar",
          "url": "media3-datasource-1.11.0-alpha01-sources.jar",
          "size": 138785,
          "sha512": "c4a1a3eeeb3f79692f0b8c6a69faf6d1a6caae60259ac18a9fdfd73786731c1dea7389b6005b2da02908cac7efaad83c02a01cf6efd3afb17d168e6d1f237280",
          "sha256": "2b8beebcbc0d2fbb39a7b9f0bc4f1121e4ba3159d9293537f6d1362ca2cf247f",
          "sha1": "d991c430b34b7590459c02370dfc53c58a3df3a0",
          "md5": "5d1f434747740944806f45737f949fc1"
        }
      ]
    }
  ]
}
