{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-test-utils",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.truth.extensions",
          "module": "truth-java8-extension",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.10.0.aar",
          "url": "media3-test-utils-1.10.0.aar",
          "size": 421799,
          "sha512": "4b6f7798a34bb097f6d4e1da33fca28af433b8c532d208f483d7cb52897230fc9e88e790839159514e16bb21aeb562b7db3e4a375297b5268dfdcd824c511744",
          "sha256": "6ee4b8fc8c12fa1418b5ccfffe901ad4ee5767ba732d024a8e407af2570f1739",
          "sha1": "d5b883169abf1039591abc4f5021671aac3fe3b0",
          "md5": "f7b5f94f058dec1d1b237458874521c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.testparameterinjector",
          "module": "test-parameter-injector",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.truth.extensions",
          "module": "truth-java8-extension",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.10.0.aar",
          "url": "media3-test-utils-1.10.0.aar",
          "size": 421799,
          "sha512": "4b6f7798a34bb097f6d4e1da33fca28af433b8c532d208f483d7cb52897230fc9e88e790839159514e16bb21aeb562b7db3e4a375297b5268dfdcd824c511744",
          "sha256": "6ee4b8fc8c12fa1418b5ccfffe901ad4ee5767ba732d024a8e407af2570f1739",
          "sha1": "d5b883169abf1039591abc4f5021671aac3fe3b0",
          "md5": "f7b5f94f058dec1d1b237458874521c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-test-utils-1.10.0-sources.jar",
          "url": "media3-test-utils-1.10.0-sources.jar",
          "size": 238948,
          "sha512": "1e64fc0d9843d39d35674f62511ed543d825273167106421cf94dd70d9ce684a078a4681eaddea5b2746a638a4d3ce303c6c029511b782bad8ce2bcfee966eb0",
          "sha256": "d58a97a539c8fb75440b3a06c9c463772ac5df3a0720fab1fe3c471041421372",
          "sha1": "24f183a4f3ae5afb07a7a4f8177f9a7098cf8bbf",
          "md5": "90085e3e0cff866c70628774a5633217"
        }
      ]
    }
  ]
}
