{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-ima",
    "version": "1.9.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.38.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.9.0-rc01.aar",
          "url": "media3-exoplayer-ima-1.9.0-rc01.aar",
          "size": 90180,
          "sha512": "86c417926c7e0f2c3d450f22b5ae8ef0e517607cbaf1c21f4cab07462a6078fe5adc286505fc24d45586e2dd1d17f55da7feb9df1278d7057f8ce9cc2c311eec",
          "sha256": "a5e5d98d7788ee7b563129c4f9444bb0840c8216036b03f431100c944742555b",
          "sha1": "cf520bca99aed890060f62883147c315617a246e",
          "md5": "628321e2c6797a7d446d43aee9d6383c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.38.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.9.0-rc01.aar",
          "url": "media3-exoplayer-ima-1.9.0-rc01.aar",
          "size": 90180,
          "sha512": "86c417926c7e0f2c3d450f22b5ae8ef0e517607cbaf1c21f4cab07462a6078fe5adc286505fc24d45586e2dd1d17f55da7feb9df1278d7057f8ce9cc2c311eec",
          "sha256": "a5e5d98d7788ee7b563129c4f9444bb0840c8216036b03f431100c944742555b",
          "sha1": "cf520bca99aed890060f62883147c315617a246e",
          "md5": "628321e2c6797a7d446d43aee9d6383c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-ima-1.9.0-rc01-sources.jar",
          "url": "media3-exoplayer-ima-1.9.0-rc01-sources.jar",
          "size": 50882,
          "sha512": "f987edce90580a9136f98a5b22b5c659cb46ef60c8dce53917614aee0cfcfe01afdd18586bc6aa8c73b645d22cb925be4b9523a6204968cbc54c5e0d7b43849b",
          "sha256": "0ee8d9240cdad6e8c490ecad9563396d6e6304c040d852c8ffd71a2ddf222841",
          "sha1": "498fa98148c0cb1196b338aa0a618a83d9c7e4e9",
          "md5": "ed13e967b1050e397b4964878cd00d9b"
        }
      ]
    }
  ]
}
