{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-transformer",
    "version": "1.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.9.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.9.0-beta01.aar",
          "url": "media3-transformer-1.9.0-beta01.aar",
          "size": 421990,
          "sha512": "07df09be3176778ee53403dce50d7b7fc0c3e45ffc738f7073454e5c5a7dc43f67c110f2ae0e91007a9ddf19451bff3c142620c6d82c791234dea38431ecc13e",
          "sha256": "9f4bfa9557a039c30da1b89c55aa277587c733062a3ab73686d73ba395ce2f00",
          "sha1": "160f9234af004c880526813eb13c6fe17bebb57c",
          "md5": "0b4c36422f37e42e0926caaabdaf303f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.9.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.9.0-beta01.aar",
          "url": "media3-transformer-1.9.0-beta01.aar",
          "size": 421990,
          "sha512": "07df09be3176778ee53403dce50d7b7fc0c3e45ffc738f7073454e5c5a7dc43f67c110f2ae0e91007a9ddf19451bff3c142620c6d82c791234dea38431ecc13e",
          "sha256": "9f4bfa9557a039c30da1b89c55aa277587c733062a3ab73686d73ba395ce2f00",
          "sha1": "160f9234af004c880526813eb13c6fe17bebb57c",
          "md5": "0b4c36422f37e42e0926caaabdaf303f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-transformer-1.9.0-beta01-sources.jar",
          "url": "media3-transformer-1.9.0-beta01-sources.jar",
          "size": 279258,
          "sha512": "c4477a3c83c6c2e0113b4fd87b68f451a55a33e3fd7c7441a9f43cab6f024e00ff1ee5968da4e4ed8361313bcb95e91bcf24f7749ffe31fc85e638a3d7359cb6",
          "sha256": "58eafea136f546b514a6d65bcbe09719ac14189f75e1cb5f19bceedc1364e699",
          "sha1": "f3edb5d2affc91d5aa7cc64ca41b185564925225",
          "md5": "6ba1cc19b56bee72e8cd06cd2185654b"
        }
      ]
    }
  ]
}
