{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-iamf",
    "version": "1.10.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0-beta01.aar",
          "url": "media3-decode-iamf-1.10.0-beta01.aar",
          "size": 11957761,
          "sha512": "8c53f37a64786b376e6fc72085fcdc1668f6f06ed54566a3bb0ebe5d82515d1c2b42cba9cc2bdce514fdde70798257de590163e681138faecf3ef94810feb03d",
          "sha256": "bbb51b01c499d07e1f456349bef64dd821b65ab5d9ee4c46f5a940ca5906e14f",
          "sha1": "b8118960f51c13599620330074f2a34790afb4e3",
          "md5": "56eb4742748992f019631b810514decc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0-beta01.aar",
          "url": "media3-decode-iamf-1.10.0-beta01.aar",
          "size": 11957761,
          "sha512": "8c53f37a64786b376e6fc72085fcdc1668f6f06ed54566a3bb0ebe5d82515d1c2b42cba9cc2bdce514fdde70798257de590163e681138faecf3ef94810feb03d",
          "sha256": "bbb51b01c499d07e1f456349bef64dd821b65ab5d9ee4c46f5a940ca5906e14f",
          "sha1": "b8118960f51c13599620330074f2a34790afb4e3",
          "md5": "56eb4742748992f019631b810514decc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0-beta01-sources.jar",
          "url": "media3-decode-iamf-1.10.0-beta01-sources.jar",
          "size": 10272,
          "sha512": "87a2f249be87db69ea205f7ade2ae7679b7692a30e9dd0b502d5469c124de88bb3c0a68d815b449bd8af36cf945817be13fdc41c891725e3ee93906754346002",
          "sha256": "cdb22503a1506ae59b5d17f6129b08f42aa5085127b02c25d09ea264e57ad47e",
          "sha1": "634607c02ce0bfba6543a372dc6584b516cf4ab4",
          "md5": "539132c136a87cb5c9df6255e8309116"
        }
      ]
    }
  ]
}
