{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-rtsp",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.2.1.aar",
          "url": "media3-exoplayer-rtsp-1.2.1.aar",
          "size": 154521,
          "sha512": "850d38423ecf701b799843e951f9b4c68e5b0c0eae9fa0105ede2586ab02206db336a3a8fd337d34696041a4397679beb67fad88460f81100f2004517cdfb292",
          "sha256": "924f704b10bfd38141f28849c4ce44d40e4d50ea6faff19d648a2e66d2af0da2",
          "sha1": "e3966b3f133b1ad735fe905906b2d43a5f1cd842",
          "md5": "e3756adbfa3d94e1d29ec87a1ebc6366"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.2.1.aar",
          "url": "media3-exoplayer-rtsp-1.2.1.aar",
          "size": 154521,
          "sha512": "850d38423ecf701b799843e951f9b4c68e5b0c0eae9fa0105ede2586ab02206db336a3a8fd337d34696041a4397679beb67fad88460f81100f2004517cdfb292",
          "sha256": "924f704b10bfd38141f28849c4ce44d40e4d50ea6faff19d648a2e66d2af0da2",
          "sha1": "e3966b3f133b1ad735fe905906b2d43a5f1cd842",
          "md5": "e3756adbfa3d94e1d29ec87a1ebc6366"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.2.1-sources.jar",
          "url": "media3-exoplayer-rtsp-1.2.1-sources.jar",
          "size": 119383,
          "sha512": "2e816bc039a0653c148aba7d0827d5e982a2abe8fa758b07cfda2ff0f4071b2dabc17a64a14790c6203fe7a2c301dc2c310aa380b1fdc6c27efa37e6fefb6e76",
          "sha256": "1c92d81b6da5bd6018b3082f0374c4fbf91459c7cbd9384511a2ba80c1767ff8",
          "sha1": "42ed81fd6ee64c6baa1d72b985022252959c1ee3",
          "md5": "c4c85d31e3d86fa77fb1ab8f454afaf4"
        }
      ]
    }
  ]
}
