{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.9.2.aar",
          "url": "media3-cast-1.9.2.aar",
          "size": 98471,
          "sha512": "919063b0828a94bd9cca46b3afc691eefe266f1fb8f5324ba329f0c95fd2119e492390bb395751ab46d557cdc96cbd161601f88f385f4ccfa37ba47f2b826ecf",
          "sha256": "15a979a22c26b957e710319a97d01da81646e5655798cac707432122aca3a126",
          "sha1": "8868e693f983ea9c023e8475190ff1ffaf250543",
          "md5": "0340462af3b8de3f56dc428a3a8e38fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.9.2.aar",
          "url": "media3-cast-1.9.2.aar",
          "size": 98471,
          "sha512": "919063b0828a94bd9cca46b3afc691eefe266f1fb8f5324ba329f0c95fd2119e492390bb395751ab46d557cdc96cbd161601f88f385f4ccfa37ba47f2b826ecf",
          "sha256": "15a979a22c26b957e710319a97d01da81646e5655798cac707432122aca3a126",
          "sha1": "8868e693f983ea9c023e8475190ff1ffaf250543",
          "md5": "0340462af3b8de3f56dc428a3a8e38fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.9.2-sources.jar",
          "url": "media3-cast-1.9.2-sources.jar",
          "size": 43143,
          "sha512": "aa2f3e73db631528b31d0d8c13a6ed96f82ff2170fcabe488a8eb5606a0a5a41dec937ee7e6d8ca53aef0eee58e9035daa48d3f98e44b969d9d27a866092a768",
          "sha256": "4c117125c156b4bbb250e46d1f017969a2f17eac6097814e9e114e43ff64247d",
          "sha1": "79a0ac06dcfc12551d0b0fa2d1b7432ea5b112ac",
          "md5": "ec1e8450647efbb0a25358f7816cc2e7"
        }
      ]
    }
  ]
}
