{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-ui-1.2.1.aar",
          "url": "media3-ui-1.2.1.aar",
          "size": 432972,
          "sha512": "939bdc565f10f5d161528000ede8871f97af85e305e19772e0afc9d19a9fcfb0bde76ece3adfa54833c27480221b07b07864f1f6a10c2b88150e0b6621041ec9",
          "sha256": "3a28d9f2d49963374f998cbdf27d5919fad9d8b0865d6809eccaf538530e8141",
          "sha1": "8f5e18c75a2f7c13f375ca27d7ed133e2b0f0756",
          "md5": "8bad34258c39ec953f1ad6b86d956639"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.2.1.aar",
          "url": "media3-ui-1.2.1.aar",
          "size": 432972,
          "sha512": "939bdc565f10f5d161528000ede8871f97af85e305e19772e0afc9d19a9fcfb0bde76ece3adfa54833c27480221b07b07864f1f6a10c2b88150e0b6621041ec9",
          "sha256": "3a28d9f2d49963374f998cbdf27d5919fad9d8b0865d6809eccaf538530e8141",
          "sha1": "8f5e18c75a2f7c13f375ca27d7ed133e2b0f0756",
          "md5": "8bad34258c39ec953f1ad6b86d956639"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.2.1-sources.jar",
          "url": "media3-ui-1.2.1-sources.jar",
          "size": 111960,
          "sha512": "56559cd9220f6c313fc3ea4c95e1860eac57c22491302a29748b94c2d2f3d5ee06ad184efef60215ccdf99164fb21960c55a834588ebc46226305a654a024f4f",
          "sha256": "96e3292a0748c74749f91314c4496ed11e8c25881652c13b23373bc5e233496b",
          "sha1": "276f7178d79b5e75db20059dfbc0ddbadac69da5",
          "md5": "5bb79c094a609460382d1c51d6b9b71b"
        }
      ]
    }
  ]
}
