{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-extractor-1.4.1.aar",
          "url": "media3-extractor-1.4.1.aar",
          "size": 774439,
          "sha512": "aabe80608426178fb551e0b2c4573438db808fecef52d27e8ca9b3317730d24b3a892eea60e9326c5554ba59245b44d298660435008a963d8625d70b87f054c9",
          "sha256": "1f51e4633e1e6137f0a4b80552afc399e269208b700352f96543d4513be6bf28",
          "sha1": "eb3c0677cb202c70ecaba0bf4a31d56a6ba607c8",
          "md5": "93879e3afeb367cdff17ba910ebab1c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.4.1.aar",
          "url": "media3-extractor-1.4.1.aar",
          "size": 774439,
          "sha512": "aabe80608426178fb551e0b2c4573438db808fecef52d27e8ca9b3317730d24b3a892eea60e9326c5554ba59245b44d298660435008a963d8625d70b87f054c9",
          "sha256": "1f51e4633e1e6137f0a4b80552afc399e269208b700352f96543d4513be6bf28",
          "sha1": "eb3c0677cb202c70ecaba0bf4a31d56a6ba607c8",
          "md5": "93879e3afeb367cdff17ba910ebab1c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.4.1-sources.jar",
          "url": "media3-extractor-1.4.1-sources.jar",
          "size": 651555,
          "sha512": "0dc517cdb31ea9665365d34fcba1b865341c37107a5ab6cea8a421858682e77a8ff06ca181d5f1d273c97edc90622a15679ae994a6847ddb10b6fb51a9f925f9",
          "sha256": "e1f27d7b6173e02f7bdb00ea88f4e47e308f1d59f67d447911ebab6d29740e47",
          "sha1": "4fa9fa75d44242406ed65ba05e2ff43681b36471",
          "md5": "447a530f9ed63a371a56518b00a93b4b"
        }
      ]
    }
  ]
}
