{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.10.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.10.0-rc01.aar",
          "url": "media3-cast-1.10.0-rc01.aar",
          "size": 114289,
          "sha512": "34cf86a63abae0581fe65b08bf747702edf04d95975a80d6b61f7a9e840e09008cb92fe3033a1711e3ebcdd891926a895ceaabb83af33913c3e606935475f23a",
          "sha256": "fd2dc65e196af337210a41f7b0c74bf4634103a03249595eb3f8436fbaac30bc",
          "sha1": "fde49eed3d2b4dce39cfa9fc156a3ff19ed54c8a",
          "md5": "24ad3a3d31f652e262e4193490629189"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.10.0-rc01.aar",
          "url": "media3-cast-1.10.0-rc01.aar",
          "size": 114289,
          "sha512": "34cf86a63abae0581fe65b08bf747702edf04d95975a80d6b61f7a9e840e09008cb92fe3033a1711e3ebcdd891926a895ceaabb83af33913c3e606935475f23a",
          "sha256": "fd2dc65e196af337210a41f7b0c74bf4634103a03249595eb3f8436fbaac30bc",
          "sha1": "fde49eed3d2b4dce39cfa9fc156a3ff19ed54c8a",
          "md5": "24ad3a3d31f652e262e4193490629189"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.10.0-rc01-sources.jar",
          "url": "media3-cast-1.10.0-rc01-sources.jar",
          "size": 53467,
          "sha512": "b76311bc4480205f2a56f0d29f56604827a8b156687f7a7b749aa18e14b23f3174a0568f72bd83925f123afd622133b8825c0222383a676a7ea988cbdddce0b0",
          "sha256": "154bd73fc83d4f5db5f76075456a241302df0b2ca59c0e4752f246c26d19873f",
          "sha1": "02099908471d7ae34034b07f54386000806cf327",
          "md5": "5a0ec529e5c6a75a3492290907127da9"
        }
      ]
    }
  ]
}
