{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.3.0.aar",
          "url": "media3-cast-1.3.0.aar",
          "size": 44504,
          "sha512": "8bfd81741508b36834c123a20df2b3734de21fc5964c8140d669cbe6f58df25b3a453b7ce8b6be6ba509c63a7ae12ad17c911e0a4824118d9bd1bfab65d0dca6",
          "sha256": "125be3f53e6982393d584f72103ba3ee11b4e29ae331c8c700e374179833fbd4",
          "sha1": "2ad86144737ca9a975da9fb17fc8666c1e0235b2",
          "md5": "cdd6955ab3b3ab6e0f1e354e47d38a01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.3.0.aar",
          "url": "media3-cast-1.3.0.aar",
          "size": 44504,
          "sha512": "8bfd81741508b36834c123a20df2b3734de21fc5964c8140d669cbe6f58df25b3a453b7ce8b6be6ba509c63a7ae12ad17c911e0a4824118d9bd1bfab65d0dca6",
          "sha256": "125be3f53e6982393d584f72103ba3ee11b4e29ae331c8c700e374179833fbd4",
          "sha1": "2ad86144737ca9a975da9fb17fc8666c1e0235b2",
          "md5": "cdd6955ab3b3ab6e0f1e354e47d38a01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.3.0-sources.jar",
          "url": "media3-cast-1.3.0-sources.jar",
          "size": 24398,
          "sha512": "fb92f45bd83f27d1dd7854fbaa5dfc000e259555c39df7885a438b7e83128642fc1ce6354e6861877ecc41170b0045a26e12b02425d1bf77e468bac13bc4e0f9",
          "sha256": "30c2a11d9244527488d9a6f9f00cde9be79220866a73416fef1f2e9783eaf287",
          "sha1": "1d6d52a7f20f1990d524abf0b11f629383b1bcac",
          "md5": "4ada4f1be4c3fac6839fd319d124a663"
        }
      ]
    }
  ]
}
