{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.10.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.10.0-rc02.aar",
          "url": "media3-cast-1.10.0-rc02.aar",
          "size": 114285,
          "sha512": "875e1b1c0c1b88e4a00c5f7a6800eb3ce496a155a89e303f5e8e88de20dfacd23a4fa66f6ad9d4228a9b3f3ff15df98bf56155640e4198f52bea8c0d6537080e",
          "sha256": "97fd2e739ad0f5054338c27849a8acaf122ececf791fed78142869eba13a9a85",
          "sha1": "4fbb14e9a2406c5f154583d5f6409e9f734d1064",
          "md5": "76317a7c1c01a2a99b820284d4548481"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.10.0-rc02.aar",
          "url": "media3-cast-1.10.0-rc02.aar",
          "size": 114285,
          "sha512": "875e1b1c0c1b88e4a00c5f7a6800eb3ce496a155a89e303f5e8e88de20dfacd23a4fa66f6ad9d4228a9b3f3ff15df98bf56155640e4198f52bea8c0d6537080e",
          "sha256": "97fd2e739ad0f5054338c27849a8acaf122ececf791fed78142869eba13a9a85",
          "sha1": "4fbb14e9a2406c5f154583d5f6409e9f734d1064",
          "md5": "76317a7c1c01a2a99b820284d4548481"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.10.0-rc02-sources.jar",
          "url": "media3-cast-1.10.0-rc02-sources.jar",
          "size": 53467,
          "sha512": "b76311bc4480205f2a56f0d29f56604827a8b156687f7a7b749aa18e14b23f3174a0568f72bd83925f123afd622133b8825c0222383a676a7ea988cbdddce0b0",
          "sha256": "154bd73fc83d4f5db5f76075456a241302df0b2ca59c0e4752f246c26d19873f",
          "sha1": "02099908471d7ae34034b07f54386000806cf327",
          "md5": "5a0ec529e5c6a75a3492290907127da9"
        }
      ]
    }
  ]
}
