{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-extractor-1.4.0.aar",
          "url": "media3-extractor-1.4.0.aar",
          "size": 774314,
          "sha512": "91180344e5d81c1a015c470037627a72a4a6ba68a9b7f9b3d1cf3cd79911521a7caa0dc78e5d97bc9d46daa43b9af2ad19b191cf3456cd5a331e9db9581b127e",
          "sha256": "113bdbb671ed8c47d922acc5f0a8f21931a2129eded95797c2e2f0e6f346ffa6",
          "sha1": "a3fb419272cf1008e3f57161807b3fd92ef965cd",
          "md5": "f1ac1a0cce1c4ad69fcb0a3cd02192ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.4.0.aar",
          "url": "media3-extractor-1.4.0.aar",
          "size": 774314,
          "sha512": "91180344e5d81c1a015c470037627a72a4a6ba68a9b7f9b3d1cf3cd79911521a7caa0dc78e5d97bc9d46daa43b9af2ad19b191cf3456cd5a331e9db9581b127e",
          "sha256": "113bdbb671ed8c47d922acc5f0a8f21931a2129eded95797c2e2f0e6f346ffa6",
          "sha1": "a3fb419272cf1008e3f57161807b3fd92ef965cd",
          "md5": "f1ac1a0cce1c4ad69fcb0a3cd02192ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.4.0-sources.jar",
          "url": "media3-extractor-1.4.0-sources.jar",
          "size": 651429,
          "sha512": "3d4e3e28da795504cc1e68a084044ffc347b5aa939d4bc58cbcd1231382572a45130a32f0a2415701fc1a6e73848e7d7fc980492468fb4b0b6b32546426c344b",
          "sha256": "2645445aec14465c7d20dbee50b27a0d8fbb082e2dae7a5a3e64da890083f4d7",
          "sha1": "6dc9f2e853f97dfc844914d312824397ef2798ef",
          "md5": "74a5398e119979bc3c933d2e722a891a"
        }
      ]
    }
  ]
}
