{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-ffmpeg",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.6.1.aar",
          "url": "media3-decode-ffmpeg-1.6.1.aar",
          "size": 3319817,
          "sha512": "4edaf9376412e050f60af5a781ffa6862064edf16fc8d8c8a586828a38e0ba70a53d6caaea14aa3c08ba05db57b0edc6f2aaf80959a525c1cbeb79944ab25dfa",
          "sha256": "da4df62b91304f21a3963295cd9243fc868c3505cb221ed028e4f3a9ad6e66a9",
          "sha1": "7eb75d6fbbe2c52f06ef758c9d2915faeb112866",
          "md5": "cb456c65a6b8bf7d24752275f1af24bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.6.1.aar",
          "url": "media3-decode-ffmpeg-1.6.1.aar",
          "size": 3319817,
          "sha512": "4edaf9376412e050f60af5a781ffa6862064edf16fc8d8c8a586828a38e0ba70a53d6caaea14aa3c08ba05db57b0edc6f2aaf80959a525c1cbeb79944ab25dfa",
          "sha256": "da4df62b91304f21a3963295cd9243fc868c3505cb221ed028e4f3a9ad6e66a9",
          "sha1": "7eb75d6fbbe2c52f06ef758c9d2915faeb112866",
          "md5": "cb456c65a6b8bf7d24752275f1af24bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.6.1-sources.jar",
          "url": "media3-decode-ffmpeg-1.6.1-sources.jar",
          "size": 11541,
          "sha512": "c5e4a8943d587b09f61987d9a1e654186f6b61264ad8eb205a3f1a414162960a817e7a10c2cdb7b2f193cb0e9aff3927456f628d7b38dcc6f929cec902bbd40c",
          "sha256": "cc60f0856dd96c505e713042ede46b5df275556a27e6e4ac22d1427907e798e7",
          "sha1": "3b44c209b2917c428fe8fc63f9d7d48657ca8023",
          "md5": "f86383552b27500b817c1731bbb539c9"
        }
      ]
    }
  ]
}
