{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.1.aar",
          "url": "media3-exoplayer-1.9.1.aar",
          "size": 1652185,
          "sha512": "43620a3a035bbe5549d14b0c577782aa640989c4c2a6d1767bad61ed4f13bedc428521b1fcd5fe8c714a41c211d18d50ee6e135876af8a3937b621d61a94d3af",
          "sha256": "a57dc448bc63be46a219c96ac8f1f306fcbe8a9523e310f381e696a02e29bc23",
          "sha1": "4bb4294364ee603273a123a033bfc98dc20cb8aa",
          "md5": "01327e0d4fbd9911eaa89d6d2b769e12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.1.aar",
          "url": "media3-exoplayer-1.9.1.aar",
          "size": 1652185,
          "sha512": "43620a3a035bbe5549d14b0c577782aa640989c4c2a6d1767bad61ed4f13bedc428521b1fcd5fe8c714a41c211d18d50ee6e135876af8a3937b621d61a94d3af",
          "sha256": "a57dc448bc63be46a219c96ac8f1f306fcbe8a9523e310f381e696a02e29bc23",
          "sha1": "4bb4294364ee603273a123a033bfc98dc20cb8aa",
          "md5": "01327e0d4fbd9911eaa89d6d2b769e12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.9.1-sources.jar",
          "url": "media3-exoplayer-1.9.1-sources.jar",
          "size": 1181696,
          "sha512": "59d03b8046ae04835a2a3f710288bbd48881e2b335ba2edbab9f855adaed2edd0dac0ac080fd5138a40ba3995846beb88b70e70d9fc4edfe0c8ac8dd11e18db0",
          "sha256": "af724cd8ea29d3590070069a9b3c2b8f51aa6cbf0b3fb04620942084124d5b99",
          "sha1": "6092e313284eaa8ad83bba03ac43ea5a02263cbc",
          "md5": "de5f401d73a157d9b676c4649e4f08c1"
        }
      ]
    }
  ]
}
