{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-ui-1.3.0.aar",
          "url": "media3-ui-1.3.0.aar",
          "size": 433080,
          "sha512": "55d670fdc9b1870e112f001f22f6b15e1dfec685ecddcbd2b3666d503afa82398cd1b01fa24fb7e84e795acca06388ac1ebfb96389a0ff95cb3719e59a46aea8",
          "sha256": "18e4ffe0722fa79b70d2bc54f537ddcede3abf08736a7e4c0968c707ddfc3833",
          "sha1": "c1183759ac59059314a0d8bb465e219bf2a03de0",
          "md5": "c111679ed110ba3c292b1846a0e8acd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.3.0.aar",
          "url": "media3-ui-1.3.0.aar",
          "size": 433080,
          "sha512": "55d670fdc9b1870e112f001f22f6b15e1dfec685ecddcbd2b3666d503afa82398cd1b01fa24fb7e84e795acca06388ac1ebfb96389a0ff95cb3719e59a46aea8",
          "sha256": "18e4ffe0722fa79b70d2bc54f537ddcede3abf08736a7e4c0968c707ddfc3833",
          "sha1": "c1183759ac59059314a0d8bb465e219bf2a03de0",
          "md5": "c111679ed110ba3c292b1846a0e8acd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.3.0-sources.jar",
          "url": "media3-ui-1.3.0-sources.jar",
          "size": 112196,
          "sha512": "9f5598ddc468b3ef303969f908e03c2052cabb967a6303df1bc1c16663abc873127a985cb2c50df396ed67e08168b5d2a1b289a0e106ee581f24caa7352a58a1",
          "sha256": "0942145f564067825b3df97194425aa3c220c5c02f9b3ae8b1bba02dc4c0a91f",
          "sha1": "6f94c3a40ac49181212e619671b5bee7fd9d86f8",
          "md5": "e1c79566cf301d737ade9391e95250e5"
        }
      ]
    }
  ]
}
