{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui-compose-material3",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-material3-1.10.0.aar",
          "url": "media3-ui-compose-material3-1.10.0.aar",
          "size": 280813,
          "sha512": "e86fa758ef10dc799b8c40b2413fd1774d617c06a2cf7580ccc56ca928102af6e1bef19cac9787481d2741672ef9bed7e1238790c5d8fb8ad5da109fa4cfbc21",
          "sha256": "0e0789cef85d948f924c0cec365021a56f6cc63b8c9888cacd05357f83e00112",
          "sha1": "c0c02617da6bcbd8ad7c40653fd46a661dccdb67",
          "md5": "ae23ee1fb2b7974d8e3a490bae0de9a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-material3-1.10.0.aar",
          "url": "media3-ui-compose-material3-1.10.0.aar",
          "size": 280813,
          "sha512": "e86fa758ef10dc799b8c40b2413fd1774d617c06a2cf7580ccc56ca928102af6e1bef19cac9787481d2741672ef9bed7e1238790c5d8fb8ad5da109fa4cfbc21",
          "sha256": "0e0789cef85d948f924c0cec365021a56f6cc63b8c9888cacd05357f83e00112",
          "sha1": "c0c02617da6bcbd8ad7c40653fd46a661dccdb67",
          "md5": "ae23ee1fb2b7974d8e3a490bae0de9a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-compose-material3-1.10.0-sources.jar",
          "url": "media3-ui-compose-material3-1.10.0-sources.jar",
          "size": 27110,
          "sha512": "6721dee37b990488baad57032dd28fa9550239661abeb38c2c2f30f4c89dada242f55d67ff056fe0e05a35e260c6a7b2977666119874e61c08cb3dd58b563945",
          "sha256": "39d11c19a6c7d982090f7b3abadc555fe6600e265e0636c128c8923bddd41009",
          "sha1": "65b8e597b41fa85ec88d79078f452dac16f5da44",
          "md5": "16a1ca86a8dfc77242ec50c5a6409be4"
        }
      ]
    }
  ]
}
