{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.6.1.aar",
          "url": "media3-common-1.6.1.aar",
          "size": 521440,
          "sha512": "f5e21857f73f6030180e170c853bbd95688a8cbc080286d27b12336fd2fbc060398d6032293c4dc67c93e3e467f3dd97af11a524bdc30596c1174b3763f46f12",
          "sha256": "c35fe2f43e1d3f41b982b5542fc7f3ee6c10ea32ab57566ac247009d16d2a40e",
          "sha1": "e4eb154d585bbbdf13879cd91705c4ba1ea6a867",
          "md5": "6e345f1b4e8086598c4b0481371ee502"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-av1",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-ffmpeg",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-flac",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-iamf",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-opus",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-vp9",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.6.1.aar",
          "url": "media3-common-1.6.1.aar",
          "size": 521440,
          "sha512": "f5e21857f73f6030180e170c853bbd95688a8cbc080286d27b12336fd2fbc060398d6032293c4dc67c93e3e467f3dd97af11a524bdc30596c1174b3763f46f12",
          "sha256": "c35fe2f43e1d3f41b982b5542fc7f3ee6c10ea32ab57566ac247009d16d2a40e",
          "sha1": "e4eb154d585bbbdf13879cd91705c4ba1ea6a867",
          "md5": "6e345f1b4e8086598c4b0481371ee502"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.6.1-sources.jar",
          "url": "media3-common-1.6.1-sources.jar",
          "size": 436546,
          "sha512": "09cb98844ef7d0701700ff508c59751d75502c3e27dc777d1cb7aadc122d9d30682f815e29c23feb294e60da051df2c0bdc3f0830c9821d9ddffc2fbbf31f5ee",
          "sha256": "3e6d466ca1d014fb77bd5ea5e5db9f388c3c9767231a0a6c286dd621104a4590",
          "sha1": "324bcb1f2d3adcfa7e06fceab9f55fe83538036c",
          "md5": "a1319427c572af9190a03063c680ef1b"
        }
      ]
    }
  ]
}
