{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-effect",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-effect-1.2.1.aar",
          "url": "media3-effect-1.2.1.aar",
          "size": 200649,
          "sha512": "60557e6c58a9e861c918b34d4aa06357c4a3d4b0b887f6263146373ccbceb2765a02261c3e8cbbc0df163462cbcdb58f5efbd83d7b1989656b2225e3a8e5c9a2",
          "sha256": "2f46d6d6c87c0d2cc6852f188107b9fb1368193a29d1389783e1d0b8b81b08df",
          "sha1": "6c438a890e93a8a571ed831486d8972c33dfb532",
          "md5": "a92b7893e399c9f1b08f45b90a47705d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.2.1.aar",
          "url": "media3-effect-1.2.1.aar",
          "size": 200649,
          "sha512": "60557e6c58a9e861c918b34d4aa06357c4a3d4b0b887f6263146373ccbceb2765a02261c3e8cbbc0df163462cbcdb58f5efbd83d7b1989656b2225e3a8e5c9a2",
          "sha256": "2f46d6d6c87c0d2cc6852f188107b9fb1368193a29d1389783e1d0b8b81b08df",
          "sha1": "6c438a890e93a8a571ed831486d8972c33dfb532",
          "md5": "a92b7893e399c9f1b08f45b90a47705d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-effect-1.2.1-sources.jar",
          "url": "media3-effect-1.2.1-sources.jar",
          "size": 145219,
          "sha512": "8a677e3297c6ff78174698872873b4c06f27420644776b6e51c776571f28b2113fd24851476a7695dde2bb22a5688e5a29539dde7d3c32ae86b324e11593e074",
          "sha256": "6a85f9f8d07a9a453f31425e92319407d8f64029cde172c39a3006f6d0907122",
          "sha1": "e08f79e5ed88c9549f9b9d48ea5c080f2fafdc3a",
          "md5": "8914e4e6d036daf65f6b9d9b09d547c2"
        }
      ]
    }
  ]
}
