{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.3.0.aar",
          "url": "media3-decode-av1-1.3.0.aar",
          "size": 2843991,
          "sha512": "f0d6016cab8b11a087b45838444682fe2eedcd58087e872f509b28562b93830fc809ca3df0679ad39db9162a54fb8f84587fbe6eb0f6e95bfa49c5e637029667",
          "sha256": "0982f3f253334aa1738e086ab203b0022caf23b3c13609404a03bc977dd2d535",
          "sha1": "127a0f7e88e541dbf979929d421a7db86a07ffe5",
          "md5": "cc34e8f5f14d393cbc364d44b33c8bd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.3.0.aar",
          "url": "media3-decode-av1-1.3.0.aar",
          "size": 2843991,
          "sha512": "f0d6016cab8b11a087b45838444682fe2eedcd58087e872f509b28562b93830fc809ca3df0679ad39db9162a54fb8f84587fbe6eb0f6e95bfa49c5e637029667",
          "sha256": "0982f3f253334aa1738e086ab203b0022caf23b3c13609404a03bc977dd2d535",
          "sha1": "127a0f7e88e541dbf979929d421a7db86a07ffe5",
          "md5": "cc34e8f5f14d393cbc364d44b33c8bd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.3.0-sources.jar",
          "url": "media3-decode-av1-1.3.0-sources.jar",
          "size": 8472,
          "sha512": "803f1f84f901196df1da36dc5220f84dc5cf82ec8fff6fc771e4aaa86ebd1005ae344abda461703be331da162b9b3fc74211351b272e360e1e713bb5233f920b",
          "sha256": "c6908bcd725350bea7259056dbd8cf2cfc227a20b899c4c82cec2b21999b25ed",
          "sha1": "ed3c893ffc01b49c06b228cb1108183f515cf8eb",
          "md5": "ae3219051225f61daefc894e6abcd7d4"
        }
      ]
    }
  ]
}
