{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-transformer",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.6.1.aar",
          "url": "media3-transformer-1.6.1.aar",
          "size": 379980,
          "sha512": "11dbdb0b531ce89cac6c47c7444119fd74794206d394d9d4ffab660676d036f470d62a0ec44ef9198fec6e8bbd674d3d3f22438e5a6c5290f72086c4046575ea",
          "sha256": "215e3c24ff4956a9bfac70ce520943a32aeafb036e31c525854bb5733f4be23d",
          "sha1": "612c252ba718cf390c4c045c4ca8abf580474694",
          "md5": "fc70d3bda561de3c71d5077506ec1243"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.6.1.aar",
          "url": "media3-transformer-1.6.1.aar",
          "size": 379980,
          "sha512": "11dbdb0b531ce89cac6c47c7444119fd74794206d394d9d4ffab660676d036f470d62a0ec44ef9198fec6e8bbd674d3d3f22438e5a6c5290f72086c4046575ea",
          "sha256": "215e3c24ff4956a9bfac70ce520943a32aeafb036e31c525854bb5733f4be23d",
          "sha1": "612c252ba718cf390c4c045c4ca8abf580474694",
          "md5": "fc70d3bda561de3c71d5077506ec1243"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-transformer-1.6.1-sources.jar",
          "url": "media3-transformer-1.6.1-sources.jar",
          "size": 256917,
          "sha512": "86ed4d91bc2fc7719b2b215997307dff7dbb417689b60451e4ba8f318a6308cb9a8c8d4af2f4dd33781e1a81ae3c5477e68a7d727c86c666a54b569fd537498b",
          "sha256": "bde3002a2cb78f331c41bd7d133288436c7d8c011e1dc911f3e629de9fc2822f",
          "sha1": "4775de20848144f6954ad18fa04fc8388f402bc0",
          "md5": "e43a09e1573a8b07851c1d49c8acb80d"
        }
      ]
    }
  ]
}
