{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-test-utils",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.truth.extensions",
          "module": "truth-java8-extension",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.8.0.aar",
          "url": "media3-test-utils-1.8.0.aar",
          "size": 384596,
          "sha512": "719b75b4400952a26a39efe4b4118b0d9d7ed97f8bae867dba4743afefb9432b74ea8a405fff27743951f894bddbdd87133029e5368beca45068d0b64b749558",
          "sha256": "07e3c51ca4f1a8a0a3aa7e3ddcab57d9d229bd9e8118d1ea29cdc6612572daca",
          "sha1": "ceb056fa21b96176517d72aa10b7514d0b7d35a0",
          "md5": "69573f9c11001f0a20d86c180aacc1a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.truth.extensions",
          "module": "truth-java8-extension",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.8.0.aar",
          "url": "media3-test-utils-1.8.0.aar",
          "size": 384596,
          "sha512": "719b75b4400952a26a39efe4b4118b0d9d7ed97f8bae867dba4743afefb9432b74ea8a405fff27743951f894bddbdd87133029e5368beca45068d0b64b749558",
          "sha256": "07e3c51ca4f1a8a0a3aa7e3ddcab57d9d229bd9e8118d1ea29cdc6612572daca",
          "sha1": "ceb056fa21b96176517d72aa10b7514d0b7d35a0",
          "md5": "69573f9c11001f0a20d86c180aacc1a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-test-utils-1.8.0-sources.jar",
          "url": "media3-test-utils-1.8.0-sources.jar",
          "size": 215634,
          "sha512": "d22a3a40a183574901a34beb6356d1bbe202843960f534623552174d69c8d1e201050038fb52ea92c39928719917e69c4fbcd277f1d2e2d4a4697f676c6548be",
          "sha256": "0045e079450b4380b6d4efef77c068b97df691259f23974596379e560f562637",
          "sha1": "9f4dfef84cf03e080af7716fe9f68d7c884c770c",
          "md5": "f4ccff25d1f8a4ab31fdb04705540d50"
        }
      ]
    }
  ]
}
