{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.4.0.aar",
          "url": "media3-decode-av1-1.4.0.aar",
          "size": 2843618,
          "sha512": "a52c80cf4f4087b827db8e6ac9b114c178fae31f5e7ab39d6bed9759f2e1f321500dc65d7c4ca4dd7984e847bc2a729c66da3bdd132e9e4c370821f21c685187",
          "sha256": "ef6a431d95ba7a72aa3af239d038c9088f188c75f674e78a5c637d38a1a1992d",
          "sha1": "14756c73de615f91721265258a5c2c02335bdea1",
          "md5": "13dc4ebf1e96133d760832be1867c204"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.4.0.aar",
          "url": "media3-decode-av1-1.4.0.aar",
          "size": 2843618,
          "sha512": "a52c80cf4f4087b827db8e6ac9b114c178fae31f5e7ab39d6bed9759f2e1f321500dc65d7c4ca4dd7984e847bc2a729c66da3bdd132e9e4c370821f21c685187",
          "sha256": "ef6a431d95ba7a72aa3af239d038c9088f188c75f674e78a5c637d38a1a1992d",
          "sha1": "14756c73de615f91721265258a5c2c02335bdea1",
          "md5": "13dc4ebf1e96133d760832be1867c204"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.4.0-sources.jar",
          "url": "media3-decode-av1-1.4.0-sources.jar",
          "size": 8109,
          "sha512": "d896390389ff39d836a3db271fccd8a955ccfaebcd4bdf1e38f6500c7036cbd6e195ea1af2e84f5d8584bf94d4e219485d4fc62c31deb8be3b371baae15886a8",
          "sha256": "a2a8d5c5fcab9e5e4dc67f91f719d16c210e783f9b5bc25aeb8099d3169e3f28",
          "sha1": "fb51559a46a9189c1c25025b6789c2558ed2e9b4",
          "md5": "b8bf0343725bf770174b9f081ec64a04"
        }
      ]
    }
  ]
}
