{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-rtsp",
    "version": "1.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.11.0-alpha01.aar",
          "url": "media3-exoplayer-rtsp-1.11.0-alpha01.aar",
          "size": 153936,
          "sha512": "2944fd1b7817c0030dab56e5ccff9ec8de49d4d5661c7c7c395c38a9321872575a0e0651ab7385d7afd3563c14535262c9659f292de3e752e8a035064276a75f",
          "sha256": "9b4b8784cb4142923c22e8e946d7fb4755f571b31ed969a3e981e2c9961f8609",
          "sha1": "8736a86ae154172707b819675e16373379f8bbae",
          "md5": "1b9f1193e60aa65b6501038f82eed400"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.11.0-alpha01.aar",
          "url": "media3-exoplayer-rtsp-1.11.0-alpha01.aar",
          "size": 153936,
          "sha512": "2944fd1b7817c0030dab56e5ccff9ec8de49d4d5661c7c7c395c38a9321872575a0e0651ab7385d7afd3563c14535262c9659f292de3e752e8a035064276a75f",
          "sha256": "9b4b8784cb4142923c22e8e946d7fb4755f571b31ed969a3e981e2c9961f8609",
          "sha1": "8736a86ae154172707b819675e16373379f8bbae",
          "md5": "1b9f1193e60aa65b6501038f82eed400"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.11.0-alpha01-sources.jar",
          "url": "media3-exoplayer-rtsp-1.11.0-alpha01-sources.jar",
          "size": 120726,
          "sha512": "16a608557d1812123da2c260dd113323a707c9633c08a4eb5621760f5442c5357b15bda4dfb45faf69b69005b2f7832213aab1bf944bee0812ffadc681945ef3",
          "sha256": "492f336e1e6e7b0c43f1ff5c08bb4718e61b7ba84ad1cb14b8db131db9dd99d6",
          "sha1": "d19cdbd9230aa732d6e9e69ee15358b9df83e96b",
          "md5": "9663715b5c40243852fa4b41ab7a7ee7"
        }
      ]
    }
  ]
}
