{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-workmanager",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-workmanager-1.4.0.aar",
          "url": "media3-exoplayer-workmanager-1.4.0.aar",
          "size": 7034,
          "sha512": "aed9429a296b514ae175e8311549b29a1fbac02573c52cc56effa2b11b7eed1d660599336d86d224964dd683b05f6a9bcdfdb55de39702611748b2f534db0d76",
          "sha256": "eefb8bd8ceb658cbd412fe8f7ede1b3bda69c7029eca325f5ff49ab6efad3bc2",
          "sha1": "fde57731d189ea7421fb3da11f51c64521ae0dcd",
          "md5": "6bf2358f27481c6d5693d14792267841"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-workmanager-1.4.0.aar",
          "url": "media3-exoplayer-workmanager-1.4.0.aar",
          "size": 7034,
          "sha512": "aed9429a296b514ae175e8311549b29a1fbac02573c52cc56effa2b11b7eed1d660599336d86d224964dd683b05f6a9bcdfdb55de39702611748b2f534db0d76",
          "sha256": "eefb8bd8ceb658cbd412fe8f7ede1b3bda69c7029eca325f5ff49ab6efad3bc2",
          "sha1": "fde57731d189ea7421fb3da11f51c64521ae0dcd",
          "md5": "6bf2358f27481c6d5693d14792267841"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-workmanager-1.4.0-sources.jar",
          "url": "media3-exoplayer-workmanager-1.4.0-sources.jar",
          "size": 3582,
          "sha512": "deffa4ac557c757b6783c3058712a53e8b0e32f01c083aff80b610812e1687ae372fc160b77c926de622fc17c9d29c944239d32d1b6d711c593c670208f57716",
          "sha256": "d56a934a669195befb19d4f1af40c8d24bef165ff4ef83b00edb784244700291",
          "sha1": "01c6a68530ae9590a2ded0a5b7e53b7b3e977dce",
          "md5": "0df83e26b3bec75e0e37060f1677eb09"
        }
      ]
    }
  ]
}
