{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.9.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.9.0-rc01.aar",
          "url": "media3-decode-opus-1.9.0-rc01.aar",
          "size": 524385,
          "sha512": "f69baa88d2adaa8031ff393b33bd67ef376e2dd3e761e7329b34182fcc6641c1046dd99b3ab501529ce4c9e551256616112b9330969d1bbe0a31f1fdd9f4b4f2",
          "sha256": "3650dcc562c29ee87d5488333529be64412a5521e6f9fd6058ad8edcdd60b856",
          "sha1": "8b8049054ad2cba95df1cdd976460a938111d96c",
          "md5": "1d5d2995e082709c4b91b2c1a009614f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.9.0-rc01.aar",
          "url": "media3-decode-opus-1.9.0-rc01.aar",
          "size": 524385,
          "sha512": "f69baa88d2adaa8031ff393b33bd67ef376e2dd3e761e7329b34182fcc6641c1046dd99b3ab501529ce4c9e551256616112b9330969d1bbe0a31f1fdd9f4b4f2",
          "sha256": "3650dcc562c29ee87d5488333529be64412a5521e6f9fd6058ad8edcdd60b856",
          "sha1": "8b8049054ad2cba95df1cdd976460a938111d96c",
          "md5": "1d5d2995e082709c4b91b2c1a009614f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.9.0-rc01-sources.jar",
          "url": "media3-decode-opus-1.9.0-rc01-sources.jar",
          "size": 9389,
          "sha512": "6ae69bf27cf39f9adf1b371006f0deeb673a68a715eeb507df9eaa8ec54c11c59c43bbb1067bae8aa286d1592d7dfd3079f97e2bdfd2da19d55ba5ac0b022f38",
          "sha256": "b69524f55a98cccab9866f181555e3a33c33cb748fc346367f44986975f0a756",
          "sha1": "1e0f2d28519f5f68576ed03548c2b01aa7460903",
          "md5": "909395e8d48ce820bb53a5eb4f96e8ee"
        }
      ]
    }
  ]
}
