{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-ffmpeg",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.3.0.aar",
          "url": "media3-decode-ffmpeg-1.3.0.aar",
          "size": 3320031,
          "sha512": "c78d80b81f0d2cc3414c71be570865dc72665d3d9e1dfcb56e2b0f30839c4869b1f87c6f7de0b1f48e460185c0ddea2e0748fa26efd72baacd86a83c41297924",
          "sha256": "968e182659e19d9ead2a9f33608972613d12216506e87bf362fbe11853f1addb",
          "sha1": "648bf0c84375a985ddeefb46c539d0ed16501888",
          "md5": "2d60fabcb4a2cb421dc3e436f3adabfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.3.0.aar",
          "url": "media3-decode-ffmpeg-1.3.0.aar",
          "size": 3320031,
          "sha512": "c78d80b81f0d2cc3414c71be570865dc72665d3d9e1dfcb56e2b0f30839c4869b1f87c6f7de0b1f48e460185c0ddea2e0748fa26efd72baacd86a83c41297924",
          "sha256": "968e182659e19d9ead2a9f33608972613d12216506e87bf362fbe11853f1addb",
          "sha1": "648bf0c84375a985ddeefb46c539d0ed16501888",
          "md5": "2d60fabcb4a2cb421dc3e436f3adabfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.3.0-sources.jar",
          "url": "media3-decode-ffmpeg-1.3.0-sources.jar",
          "size": 11904,
          "sha512": "12b36686fcd0bbaa6f54a323915e953ed6f9726221871a951787ada69229228b49dc2cd6ee6ab4ed4586e570f4df1f60175037b5db747f88ed7a66e13dee5f8d",
          "sha256": "c96a086bcd2c24fa503faace3aa4ea580166c1d334dd80f7e2d45adb008324bf",
          "sha1": "6eaa69ed619da98d36cc24ba021d606193fc36cb",
          "md5": "64e7e388dfd564ef3010cc82ef81dec2"
        }
      ]
    }
  ]
}
