{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.9.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-rc01.aar",
          "url": "media3-exoplayer-1.9.0-rc01.aar",
          "size": 1649319,
          "sha512": "97fb77dcbb66254a91bf040702f8f478ac66827e206df098067d40b0119030d24adb15923b8dcc90c91ec470fc81700f423ecca84c262a19a1b6674f6f7ac968",
          "sha256": "90e07e2c8a2b8ff7665b3f8689e7afa564d3f0692eeed8b8115e76c9f2cae269",
          "sha1": "6bcb297ffd69f9046fd2a23f61c3ed93007ad444",
          "md5": "c79ba55f32bf49892cf1f77ef313a5cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-rc01.aar",
          "url": "media3-exoplayer-1.9.0-rc01.aar",
          "size": 1649319,
          "sha512": "97fb77dcbb66254a91bf040702f8f478ac66827e206df098067d40b0119030d24adb15923b8dcc90c91ec470fc81700f423ecca84c262a19a1b6674f6f7ac968",
          "sha256": "90e07e2c8a2b8ff7665b3f8689e7afa564d3f0692eeed8b8115e76c9f2cae269",
          "sha1": "6bcb297ffd69f9046fd2a23f61c3ed93007ad444",
          "md5": "c79ba55f32bf49892cf1f77ef313a5cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-rc01-sources.jar",
          "url": "media3-exoplayer-1.9.0-rc01-sources.jar",
          "size": 1178877,
          "sha512": "67894b50c605cbd01e3bec8143ea76dae8057394347db70408b25cc76c8667763b72d38f22c9ef4ff009d435a3ac19c220c3dfeb30cfea2023e1ad86a3b39934",
          "sha256": "117b184b95b1752955a1a1fbfaa1aebf29f3575900f08acde59ecaaf14efe620",
          "sha1": "5d4d33ee39f0fefeb6a036d6c0c88e50bd15b0bb",
          "md5": "0902cb3d76684f10839d162db23f77c3"
        }
      ]
    }
  ]
}
