{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-av1",
    "version": "1.11.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-rc01.aar",
          "url": "media3-decoder-av1-1.11.0-rc01.aar",
          "size": 2292454,
          "sha512": "e86cfa7d650f42f0d140bde03b649120eafbc5c3e15e2dc8abdaf0255fb408b9e5b4568bb634318f75bc671a03b42d64cfe657f8ca085408ceb8e0f032774ab9",
          "sha256": "98cee23df96ce06b4066416ae91413f9c445b2448c68bb17a98127be1aa92208",
          "sha1": "e972211d5426799eb27cd61f47db69877f2252d0",
          "md5": "8a28346f59a8bb1c9dcb0f488a3f2758"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-rc01.aar",
          "url": "media3-decoder-av1-1.11.0-rc01.aar",
          "size": 2292454,
          "sha512": "e86cfa7d650f42f0d140bde03b649120eafbc5c3e15e2dc8abdaf0255fb408b9e5b4568bb634318f75bc671a03b42d64cfe657f8ca085408ceb8e0f032774ab9",
          "sha256": "98cee23df96ce06b4066416ae91413f9c445b2448c68bb17a98127be1aa92208",
          "sha1": "e972211d5426799eb27cd61f47db69877f2252d0",
          "md5": "8a28346f59a8bb1c9dcb0f488a3f2758"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-rc01-sources.jar",
          "url": "media3-decoder-av1-1.11.0-rc01-sources.jar",
          "size": 11543,
          "sha512": "f6885d2a7c0c88a9dcedd2dc276f9d5a19a5783237b69f6980f8d5b00b046cfa10c8d3db9961536d62581c2ce38935b9d4dec38f4b71f32c4436f6d98be12cd7",
          "sha256": "332832813bd15ebde22ca951a5dbbffd7dc6e9c3ed1cdc60f58f7cb7dc4596e3",
          "sha1": "27fbcdc7214fa6d87fc64e24f1d581040d209b17",
          "md5": "0e46ed2c1f5449ab0becff6c2cdf38a1"
        }
      ]
    }
  ]
}
