{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.9.1.aar",
          "url": "media3-decode-opus-1.9.1.aar",
          "size": 524363,
          "sha512": "1f5549e2369e5bc3ef59d1bd238adcbe53394009a50841cb6023b37393424a15bb2b79d8409cced075ff2e9fadce5d469f9a5a1008edf52f6c42219965bc5631",
          "sha256": "acb02cb05113a2acfc09c141de83b584235fc6f98e805d4d61abd8384a9503d7",
          "sha1": "8c0a0999b85e74faf560f18c5a515ded45a0cfda",
          "md5": "3e1d181cf397091c4a95df3fdf984247"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.9.1.aar",
          "url": "media3-decode-opus-1.9.1.aar",
          "size": 524363,
          "sha512": "1f5549e2369e5bc3ef59d1bd238adcbe53394009a50841cb6023b37393424a15bb2b79d8409cced075ff2e9fadce5d469f9a5a1008edf52f6c42219965bc5631",
          "sha256": "acb02cb05113a2acfc09c141de83b584235fc6f98e805d4d61abd8384a9503d7",
          "sha1": "8c0a0999b85e74faf560f18c5a515ded45a0cfda",
          "md5": "3e1d181cf397091c4a95df3fdf984247"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.9.1-sources.jar",
          "url": "media3-decode-opus-1.9.1-sources.jar",
          "size": 9389,
          "sha512": "6ae69bf27cf39f9adf1b371006f0deeb673a68a715eeb507df9eaa8ec54c11c59c43bbb1067bae8aa286d1592d7dfd3079f97e2bdfd2da19d55ba5ac0b022f38",
          "sha256": "b69524f55a98cccab9866f181555e3a33c33cb748fc346367f44986975f0a756",
          "sha1": "1e0f2d28519f5f68576ed03548c2b01aa7460903",
          "md5": "909395e8d48ce820bb53a5eb4f96e8ee"
        }
      ]
    }
  ]
}
