{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-flac",
    "version": "1.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.9.0-beta01.aar",
          "url": "media3-decode-flac-1.9.0-beta01.aar",
          "size": 580278,
          "sha512": "32c00cc180cf6b533db08999ed2cbe092babb25fbbcc9c3c4d664d68dec4adfcebf61b4349ddf95554de4611e68f202250622773218e1054b91cda71bb239e41",
          "sha256": "b448b15c91e835b912d97e0b768460d1058ac9aa54d085a4f5141f1d15bb9b14",
          "sha1": "dcc8261b16805f96bec7efc278f1a68e684f67d9",
          "md5": "24a6e930b9f7ff0bf4adf2622c3a86b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.9.0-beta01.aar",
          "url": "media3-decode-flac-1.9.0-beta01.aar",
          "size": 580278,
          "sha512": "32c00cc180cf6b533db08999ed2cbe092babb25fbbcc9c3c4d664d68dec4adfcebf61b4349ddf95554de4611e68f202250622773218e1054b91cda71bb239e41",
          "sha256": "b448b15c91e835b912d97e0b768460d1058ac9aa54d085a4f5141f1d15bb9b14",
          "sha1": "dcc8261b16805f96bec7efc278f1a68e684f67d9",
          "md5": "24a6e930b9f7ff0bf4adf2622c3a86b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-flac-1.9.0-beta01-sources.jar",
          "url": "media3-decode-flac-1.9.0-beta01-sources.jar",
          "size": 15748,
          "sha512": "ace6d2a23a3ac31f89c72e99fa5e525e1dd02184583e2260ae39c102b8f3bbc891ae90e58e640e3e1a9bbc84511366521732ffe6edab21a47bb3ebc904e92e74",
          "sha256": "636547d168b74eb6dde49727aa1b5430eb79b5b86cc77808dd9aaa44dfa948dc",
          "sha1": "648f0d2d5ae45d632506a44abcc31d234c370b97",
          "md5": "26cc69a7600a7b8a9561233647815276"
        }
      ]
    }
  ]
}
