{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui-compose",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-1.9.1.aar",
          "url": "media3-ui-compose-1.9.1.aar",
          "size": 165795,
          "sha512": "cf9bd5378d5657f6bc69a2697e19ed30837224ea4a353ac009df4135a601d8318df30e42c6fd48d4ec35263be309e88aa629a920117953d2f24be0938e2daabe",
          "sha256": "3c5a37f99fe62b41860953bcaebb8e483fce55d4c7ce9e9d5be6453e96dd0ba4",
          "sha1": "c53af6aa501d5b31071674c2683b096139ec0b8f",
          "md5": "739e14f9e5e824bfcec651479aaae545"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-1.9.1.aar",
          "url": "media3-ui-compose-1.9.1.aar",
          "size": 165795,
          "sha512": "cf9bd5378d5657f6bc69a2697e19ed30837224ea4a353ac009df4135a601d8318df30e42c6fd48d4ec35263be309e88aa629a920117953d2f24be0938e2daabe",
          "sha256": "3c5a37f99fe62b41860953bcaebb8e483fce55d4c7ce9e9d5be6453e96dd0ba4",
          "sha1": "c53af6aa501d5b31071674c2683b096139ec0b8f",
          "md5": "739e14f9e5e824bfcec651479aaae545"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-compose-1.9.1-sources.jar",
          "url": "media3-ui-compose-1.9.1-sources.jar",
          "size": 41320,
          "sha512": "3d5df9e9e138393d3648be90f47872f1cc883c0597ed06ee9b34769e830644522eca2603802d5e552de9be0bd3f5f581597f7816ec8548f91fb175b2420587da",
          "sha256": "c5e1a31e1e6e828a058e4dd7b11dac7b82b58819c5ebcbaef92a1a1128f3f1b5",
          "sha1": "186d6360000d1d46a448a9e6b994f984db8a0975",
          "md5": "9a59df22ca8ac73fa591486e737f2dd1"
        }
      ]
    }
  ]
}
