{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-dash",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.3.0.aar",
          "url": "media3-exoplayer-dash-1.3.0.aar",
          "size": 139392,
          "sha512": "df70d65bda3a07e608d57dd0461f544eb8298203c0641c24bb09a6197e82123d0d7351a216b7f12c5d73817e6e159ee00104c245da86a237ab8626e1340b1aa9",
          "sha256": "927c52ff17e69524b1ae0962cf7e8341a4206b3e230b5fb05c24e198b02fcb56",
          "sha1": "6d405154e4678eda279a99c8626db2a39c78dcdf",
          "md5": "2aa8688345e718ac759a43e7d2098239"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-dash-1.3.0.aar",
          "url": "media3-exoplayer-dash-1.3.0.aar",
          "size": 139392,
          "sha512": "df70d65bda3a07e608d57dd0461f544eb8298203c0641c24bb09a6197e82123d0d7351a216b7f12c5d73817e6e159ee00104c245da86a237ab8626e1340b1aa9",
          "sha256": "927c52ff17e69524b1ae0962cf7e8341a4206b3e230b5fb05c24e198b02fcb56",
          "sha1": "6d405154e4678eda279a99c8626db2a39c78dcdf",
          "md5": "2aa8688345e718ac759a43e7d2098239"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.3.0-sources.jar",
          "url": "media3-exoplayer-dash-1.3.0-sources.jar",
          "size": 94003,
          "sha512": "13213401cb8e07e88860b8c8f9b8a611b0fdf2f7c29783cf6685952ed947860613e5e1daceacf12addfe41f07641d2fba32aee6b16546dc0bcee9efcb4443b62",
          "sha256": "7b4df14b38ded53546faeffedfc0ee5e3dbb000df6ad79e1566336a4c55c2b2c",
          "sha1": "f31d513eb284960bc9f9aef3740c55e2f6db5baa",
          "md5": "4d56bcbd6ae26a5df2af52d9a284f756"
        }
      ]
    }
  ]
}
