{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-test-utils-robolectric",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-test-utils-robolectric-1.2.0.aar",
          "url": "media3-test-utils-robolectric-1.2.0.aar",
          "size": 25957,
          "sha512": "67688dbbfb892d41f92a5fff24258a1e55ec416385bcb0971002aaaa75c15726bdca050a416f9fe2281043d306144b6d59c0542a794b87f13b7e12a0300015b0",
          "sha256": "ec977b615c4e3bbd31ebc54a3e3e60e50d69a2182284649f061e4c35775d8acd",
          "sha1": "69e368b42088ca867a225bf6abd707e4a8e01194",
          "md5": "d02f30aee284e6de3320a051d403d06c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.10.3"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-robolectric-1.2.0.aar",
          "url": "media3-test-utils-robolectric-1.2.0.aar",
          "size": 25957,
          "sha512": "67688dbbfb892d41f92a5fff24258a1e55ec416385bcb0971002aaaa75c15726bdca050a416f9fe2281043d306144b6d59c0542a794b87f13b7e12a0300015b0",
          "sha256": "ec977b615c4e3bbd31ebc54a3e3e60e50d69a2182284649f061e4c35775d8acd",
          "sha1": "69e368b42088ca867a225bf6abd707e4a8e01194",
          "md5": "d02f30aee284e6de3320a051d403d06c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-test-utils-robolectric-1.2.0-sources.jar",
          "url": "media3-test-utils-robolectric-1.2.0-sources.jar",
          "size": 15838,
          "sha512": "7229dd26ef6d8b9bf0e189c4e041d02880fb1c00a5eb9ac0a053151e5bef31b192a0b7e8597ac306baaaba48806a73774f55f0fac9fdfb20ab887bf2148f673c",
          "sha256": "8e87002e978130dd78edcb28237cf6239a68f97b36b6fc55225e3d5eb1c11899",
          "sha1": "49178c06f4a4386cd0b1109465457f5177bcc677",
          "md5": "a6b0f2d935eb34a6d85de15a3321b1d5"
        }
      ]
    }
  ]
}
