{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.6.1.aar",
          "url": "media3-datasource-1.6.1.aar",
          "size": 165639,
          "sha512": "359afd48c7efc28f5e10e064ed84922402910d2e08e9a3dca78c008a5dba12b423e4fb96dfdb893aee0371664518ef2c4225f75f0bdd7444b5947e30ba4b3edc",
          "sha256": "97f15fc2e69bb5ce0f162366a8effea4e9303c0627f6dd2b68913f90c6da0f1b",
          "sha1": "59b294974db5d7e37ba35c35191eac54ba713e6a",
          "md5": "34159db60c3b39a9da32a972977ab26a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.6.1.aar",
          "url": "media3-datasource-1.6.1.aar",
          "size": 165639,
          "sha512": "359afd48c7efc28f5e10e064ed84922402910d2e08e9a3dca78c008a5dba12b423e4fb96dfdb893aee0371664518ef2c4225f75f0bdd7444b5947e30ba4b3edc",
          "sha256": "97f15fc2e69bb5ce0f162366a8effea4e9303c0627f6dd2b68913f90c6da0f1b",
          "sha1": "59b294974db5d7e37ba35c35191eac54ba713e6a",
          "md5": "34159db60c3b39a9da32a972977ab26a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.6.1-sources.jar",
          "url": "media3-datasource-1.6.1-sources.jar",
          "size": 137419,
          "sha512": "7fd12e8aa041052055783790632792701d9dabd0ba9fdeb084de348b45ce8645a7d97d7f98276b5bcd7a6e837ba6d289664ee018c56f29d6ae53cb8688e17658",
          "sha256": "d62d1d34ade715f5bd0e9c43b8daa224f2fc54b8a9435e5f3e51401372d27613",
          "sha1": "7a4e0709a975c37cc1af0d0d5a601525d48430be",
          "md5": "78aae5ab0ede0c7f808f44140baba5f3"
        }
      ]
    }
  ]
}
