{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-ima",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.3.0.aar",
          "url": "media3-exoplayer-ima-1.3.0.aar",
          "size": 112916,
          "sha512": "e4ff7eb072b6e14af26f4c1ab3fc1e84f48846711eb9fc7cefbedcb452623e29144d5b19be7ded5dcba24fc536f671bf6f876bb67bd8ab5dbcc08b267ba49ea9",
          "sha256": "5981d275c2cd5ffa1b418ea096eed074ef8ffaae58018514fdb4b33a69bf66c9",
          "sha1": "9f33d0e2241dbec7f942451406c5297f80414ba5",
          "md5": "38c3054e209ff194ad2bde77200d8aa0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.3.0.aar",
          "url": "media3-exoplayer-ima-1.3.0.aar",
          "size": 112916,
          "sha512": "e4ff7eb072b6e14af26f4c1ab3fc1e84f48846711eb9fc7cefbedcb452623e29144d5b19be7ded5dcba24fc536f671bf6f876bb67bd8ab5dbcc08b267ba49ea9",
          "sha256": "5981d275c2cd5ffa1b418ea096eed074ef8ffaae58018514fdb4b33a69bf66c9",
          "sha1": "9f33d0e2241dbec7f942451406c5297f80414ba5",
          "md5": "38c3054e209ff194ad2bde77200d8aa0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-ima-1.3.0-sources.jar",
          "url": "media3-exoplayer-ima-1.3.0-sources.jar",
          "size": 50370,
          "sha512": "5a2e1e7bbe4f20c56cf6573e79b9538f8332161c36c49ce57d71045257139021bf3ad0351c7e37fec3eab03c62bb64dfbcbc109fd0c86f353ebac1dc2c9c3ff5",
          "sha256": "7b7d5f2c0353a8f9fca5d3b5da45c24252c5bc3cb7d228aabd3c96a7ca8e05ef",
          "sha1": "8138bd0e37a69a2c600d60584129f7419ce51923",
          "md5": "95b7c525da880a6af2803259cbd2703b"
        }
      ]
    }
  ]
}
