{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.9.1.aar",
          "url": "media3-extractor-1.9.1.aar",
          "size": 803600,
          "sha512": "92f30663a5d989d5247dd2607c7ffe5f7dd3ca89d717e47e4c8abee63dde70b9573757e7a96a72f162417ad7a6652371ba41fb1fa191f2ff31135a5d06fe639b",
          "sha256": "dabbc6029d7563e364dc3e377e7b10fb160baaa90a2a9fddf51111e6affff62e",
          "sha1": "66f953eb593371a97eb6edf04d7ac8d071c11958",
          "md5": "086e1bd31f329bc01c8dc76f182e60d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.9.1.aar",
          "url": "media3-extractor-1.9.1.aar",
          "size": 803600,
          "sha512": "92f30663a5d989d5247dd2607c7ffe5f7dd3ca89d717e47e4c8abee63dde70b9573757e7a96a72f162417ad7a6652371ba41fb1fa191f2ff31135a5d06fe639b",
          "sha256": "dabbc6029d7563e364dc3e377e7b10fb160baaa90a2a9fddf51111e6affff62e",
          "sha1": "66f953eb593371a97eb6edf04d7ac8d071c11958",
          "md5": "086e1bd31f329bc01c8dc76f182e60d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.9.1-sources.jar",
          "url": "media3-extractor-1.9.1-sources.jar",
          "size": 695423,
          "sha512": "f038c173ac37ee923aefec866f7cffde6206acb349e858f43db197ada9f1c52f88367a96552d5213d3dffd69b9dc908e6286ef652cfa70d4e9301fbd06479445",
          "sha256": "579910c21c190dd8bacb32db0cbc5336bb45c3940064f995500955368a5cd2bd",
          "sha1": "2a723125b1cf890633be1eee5e65048efa33a394",
          "md5": "66e300e3f431208f00f1c42f259e74c8"
        }
      ]
    }
  ]
}
