{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.6.1.aar",
          "url": "media3-decode-opus-1.6.1.aar",
          "size": 512365,
          "sha512": "f4266683e48c3ddc826a50d162f48ae0d98dc42dfb93e9fa1d84e7d82617751a8c643ce4a3eb114d9465b9290488f5302d83e5132c654521b7f1eee5093e032d",
          "sha256": "12704ddf1d5486ea6353927af30732f56e478b16ac58f5c042e85175bdf61b1b",
          "sha1": "288b4877c09faa35cb51174e8505c53d8ceb0fbc",
          "md5": "98c2d40a2f16534fa703ea7a3d39c50f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.6.1.aar",
          "url": "media3-decode-opus-1.6.1.aar",
          "size": 512365,
          "sha512": "f4266683e48c3ddc826a50d162f48ae0d98dc42dfb93e9fa1d84e7d82617751a8c643ce4a3eb114d9465b9290488f5302d83e5132c654521b7f1eee5093e032d",
          "sha256": "12704ddf1d5486ea6353927af30732f56e478b16ac58f5c042e85175bdf61b1b",
          "sha1": "288b4877c09faa35cb51174e8505c53d8ceb0fbc",
          "md5": "98c2d40a2f16534fa703ea7a3d39c50f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.6.1-sources.jar",
          "url": "media3-decode-opus-1.6.1-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
