{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0.aar",
          "url": "media3-exoplayer-1.9.0.aar",
          "size": 1649305,
          "sha512": "02ff7fb0c9307f94cb8c95cd9e472947c759f4d02a88e46e06fe573acbdac6c3b98becafd902f644913e086724afe87389f39abbe949606a1ff15952d732a41a",
          "sha256": "558cea19e5808fef3243c68bdec969108609a7b0ce9809e5e4906558b792f635",
          "sha1": "8112bcaae0bf60bbd5c08abee823cbf5bf028626",
          "md5": "b00d03d366827a18c19ea79075931c25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0.aar",
          "url": "media3-exoplayer-1.9.0.aar",
          "size": 1649305,
          "sha512": "02ff7fb0c9307f94cb8c95cd9e472947c759f4d02a88e46e06fe573acbdac6c3b98becafd902f644913e086724afe87389f39abbe949606a1ff15952d732a41a",
          "sha256": "558cea19e5808fef3243c68bdec969108609a7b0ce9809e5e4906558b792f635",
          "sha1": "8112bcaae0bf60bbd5c08abee823cbf5bf028626",
          "md5": "b00d03d366827a18c19ea79075931c25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-sources.jar",
          "url": "media3-exoplayer-1.9.0-sources.jar",
          "size": 1178877,
          "sha512": "67894b50c605cbd01e3bec8143ea76dae8057394347db70408b25cc76c8667763b72d38f22c9ef4ff009d435a3ac19c220c3dfeb30cfea2023e1ad86a3b39934",
          "sha256": "117b184b95b1752955a1a1fbfaa1aebf29f3575900f08acde59ecaaf14efe620",
          "sha1": "5d4d33ee39f0fefeb6a036d6c0c88e50bd15b0bb",
          "md5": "0902cb3d76684f10839d162db23f77c3"
        }
      ]
    }
  ]
}
