{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.0.aar",
          "url": "media3-exoplayer-1.10.0.aar",
          "size": 1690778,
          "sha512": "8ff92e31e479192664c829f3975a638065c5e4cc44c686d3eaf6a55547746f38fcee56ba3a52fdbf013000db152d888234c1b3ed37c598e2cb81c3286cf569ea",
          "sha256": "d424dbab630d50b41b4973779da736544ba86325706eb8342676e209bacd6881",
          "sha1": "69f908e3a892abe27acb6eb2045c5cbe4b197182",
          "md5": "a33a5286f15b959c087a9ef9c09f4290"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.0.aar",
          "url": "media3-exoplayer-1.10.0.aar",
          "size": 1690778,
          "sha512": "8ff92e31e479192664c829f3975a638065c5e4cc44c686d3eaf6a55547746f38fcee56ba3a52fdbf013000db152d888234c1b3ed37c598e2cb81c3286cf569ea",
          "sha256": "d424dbab630d50b41b4973779da736544ba86325706eb8342676e209bacd6881",
          "sha1": "69f908e3a892abe27acb6eb2045c5cbe4b197182",
          "md5": "a33a5286f15b959c087a9ef9c09f4290"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.10.0-sources.jar",
          "url": "media3-exoplayer-1.10.0-sources.jar",
          "size": 1215574,
          "sha512": "c57b89ac062a401eeed1092ea72a877714e8991c6b0ec2bb2de935d30596f4769cefad39c1d0f6bd8b51eea3650cd1e1134738ac66050f150e94d3a27891b139",
          "sha256": "5c7a47e479f8f06e65397edd3c9a332d11849e24bd07b0011ec936d7d24d0730",
          "sha1": "e89e34ae71c33afc512523d629a6017c3fa7069f",
          "md5": "1ad83310fac875bca063bc21cd926b1e"
        }
      ]
    }
  ]
}
