{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-midi",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-midi-1.3.0.aar",
          "url": "media3-exoplayer-midi-1.3.0.aar",
          "size": 271312,
          "sha512": "4421b23aacd241a2f75a17e1285c8f924bb5e35bca831d3d6674e5bf4e64c04642da53ecb376b5c4fc97a3324da81a00fdd408fbe97d542cff7482c0c552bf60",
          "sha256": "e62e49bb706c6908e6152ce8ea5f94afbfbd86eab672e7630e24a41937ecde47",
          "sha1": "b372bc6841aabcda6006e3d775919571ba5a7172",
          "md5": "a535450bfe2d49fba82f6115c7600ea7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.philburk",
          "module": "jsyn",
          "version": {
            "requires": "40a41092cbab558d7d410ec43d93bb1e4121e86a"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-midi-1.3.0.aar",
          "url": "media3-exoplayer-midi-1.3.0.aar",
          "size": 271312,
          "sha512": "4421b23aacd241a2f75a17e1285c8f924bb5e35bca831d3d6674e5bf4e64c04642da53ecb376b5c4fc97a3324da81a00fdd408fbe97d542cff7482c0c552bf60",
          "sha256": "e62e49bb706c6908e6152ce8ea5f94afbfbd86eab672e7630e24a41937ecde47",
          "sha1": "b372bc6841aabcda6006e3d775919571ba5a7172",
          "md5": "a535450bfe2d49fba82f6115c7600ea7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-midi-1.3.0-sources.jar",
          "url": "media3-exoplayer-midi-1.3.0-sources.jar",
          "size": 35390,
          "sha512": "7f82048c4ebf6f658c98930a19fc25cb75acf21aa635eb7ee8d51dde3ecdb7e7312d3a7bbfc2d5f8e7d8d8bc6447eaab5949c374a7d44c9e652d8d86f4675556",
          "sha256": "cc6ac0e1d22be80aaab398f21b6dc13ec63ba4a66138d0c2ba6cb980f47caadc",
          "sha1": "3044ea4d2578bde8cce3b29a88c8cd744a14a4ab",
          "md5": "23718b465d52acbd188f05e90263a52f"
        }
      ]
    }
  ]
}
