{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-ima",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.2.1.aar",
          "url": "media3-exoplayer-ima-1.2.1.aar",
          "size": 112901,
          "sha512": "f8fe13f10976b547bebc05db8fe3c65d42b13117949205f44736af7f7d53d441baccece37bacb20b46ca642701b18af68a35d35b22d3ddeab98621300f23d793",
          "sha256": "1b19bcd6d425053eef0bca8037d296576ff15c1c5bcc9a109f4d3193206a376d",
          "sha1": "0ab53dd535b4736e3c51d156817f51676027789f",
          "md5": "2175a073b99db699912f26c76a8f414d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.2.1.aar",
          "url": "media3-exoplayer-ima-1.2.1.aar",
          "size": 112901,
          "sha512": "f8fe13f10976b547bebc05db8fe3c65d42b13117949205f44736af7f7d53d441baccece37bacb20b46ca642701b18af68a35d35b22d3ddeab98621300f23d793",
          "sha256": "1b19bcd6d425053eef0bca8037d296576ff15c1c5bcc9a109f4d3193206a376d",
          "sha1": "0ab53dd535b4736e3c51d156817f51676027789f",
          "md5": "2175a073b99db699912f26c76a8f414d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-ima-1.2.1-sources.jar",
          "url": "media3-exoplayer-ima-1.2.1-sources.jar",
          "size": 50344,
          "sha512": "ba5efbc175c72c25ce98f0d1b8d29a33d5d95ce249b94a5434e6bf288e4177f694ac18f7158d4d95984b0be89f46af761dff8607dee95cc09c79a41238ce4cbc",
          "sha256": "fdb99bb2ab39a9b65c44bae0941c119e08a9d89f4de044ef02b1b6198783c19b",
          "sha1": "d16dc7f476b638cc6faf34c0caad8932a59c3e01",
          "md5": "304b219fb2045015a23e40e4df92cb1c"
        }
      ]
    }
  ]
}
