{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-smoothstreaming",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.10.0.aar",
          "url": "media3-exoplayer-smoothstreaming-1.10.0.aar",
          "size": 53202,
          "sha512": "8f4f325b8fd80bf9b415172453b6c79c1b9144ab766c1baeaf70562e6fb5c2bed0f63a1d287131ee3664b6e19c740e2209d59c3827cd4f4a4304e410ccf012cc",
          "sha256": "5ffd2036ba5134e400f21028181eb4b1e756788e899030a19872e4b5b0fa103a",
          "sha1": "1f7f887420dda8b13f9c362b8e972772292e1e2b",
          "md5": "0f8eff282d4257df96503fab54f3db68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.10.0.aar",
          "url": "media3-exoplayer-smoothstreaming-1.10.0.aar",
          "size": 53202,
          "sha512": "8f4f325b8fd80bf9b415172453b6c79c1b9144ab766c1baeaf70562e6fb5c2bed0f63a1d287131ee3664b6e19c740e2209d59c3827cd4f4a4304e410ccf012cc",
          "sha256": "5ffd2036ba5134e400f21028181eb4b1e756788e899030a19872e4b5b0fa103a",
          "sha1": "1f7f887420dda8b13f9c362b8e972772292e1e2b",
          "md5": "0f8eff282d4257df96503fab54f3db68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.10.0-sources.jar",
          "url": "media3-exoplayer-smoothstreaming-1.10.0-sources.jar",
          "size": 31775,
          "sha512": "33e69478bb581cbb1f61fc3519876a5730930650121cd96c5705fa7b89e885f6fac61434510d940e9087431b93f8f6cb23355cff7fca4891c4fbabe09ffa19ba",
          "sha256": "6fa71005f82ab72f1bee376fd4529dc66e93df3c5dce41e95d12e310dc5c82fb",
          "sha1": "181fb5674c7a79cc7127372613bb879d76ca376d",
          "md5": "fe596f02de17135c5ea67a7f5a552c1b"
        }
      ]
    }
  ]
}
