{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-container",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-container-1.2.1.aar",
          "url": "media3-container-1.2.1.aar",
          "size": 23301,
          "sha512": "a43a580ad2f865588edbf5fb3db641b212177aca91d91e74151c2a4aae7fddd2fa86e10df36612af955d713e511947afe577239db770bd20b3e39c0af5d5d2bc",
          "sha256": "d11685dee734b16851c06b255921d6d3fdf8206f22b7f9979bfb29282a00b9e7",
          "sha1": "7c52c9c04870cad34df3f449ad37de3f3ff6810a",
          "md5": "5343200f0ee3d5ca4686fd108b0dbc44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.2.1.aar",
          "url": "media3-container-1.2.1.aar",
          "size": 23301,
          "sha512": "a43a580ad2f865588edbf5fb3db641b212177aca91d91e74151c2a4aae7fddd2fa86e10df36612af955d713e511947afe577239db770bd20b3e39c0af5d5d2bc",
          "sha256": "d11685dee734b16851c06b255921d6d3fdf8206f22b7f9979bfb29282a00b9e7",
          "sha1": "7c52c9c04870cad34df3f449ad37de3f3ff6810a",
          "md5": "5343200f0ee3d5ca4686fd108b0dbc44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-container-1.2.1-sources.jar",
          "url": "media3-container-1.2.1-sources.jar",
          "size": 18971,
          "sha512": "fad3c18cfe6ca462ae0bb2955c20eb296e9764a0845da3453179222789902c8a901db398fbe7ae80373bc14b398aaca0cb992c05cd77e8e058e2341c3ad6c2ac",
          "sha256": "992ca449a325c03b376a5d88e5f8d5f924ce740e94cc70ef61812c5e3e32ba72",
          "sha1": "b622989777b3ac1432a8301343f441487e1d7885",
          "md5": "fe188e3b4ced34bace596a54a0359c51"
        }
      ]
    }
  ]
}
