{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.1.aar",
          "url": "media3-exoplayer-1.10.1.aar",
          "size": 1693238,
          "sha512": "b60afe2d3ca80c28fa5721667d5f11c4743f9c2a8749e9de7e0e10f68700de6b69a4027bff81a1dd361c9a207196d3d6e8ab7659a843e508ee0fa0eaa94ed677",
          "sha256": "c19bca72cde9b26046e47f110441e31c5e7a3d493290de2af206043b584a83f9",
          "sha1": "43a02808e4c31b1c8fe60fc7a9e7e69d79636d99",
          "md5": "c7466d738370c4b94e15a8274d73c8b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.1.aar",
          "url": "media3-exoplayer-1.10.1.aar",
          "size": 1693238,
          "sha512": "b60afe2d3ca80c28fa5721667d5f11c4743f9c2a8749e9de7e0e10f68700de6b69a4027bff81a1dd361c9a207196d3d6e8ab7659a843e508ee0fa0eaa94ed677",
          "sha256": "c19bca72cde9b26046e47f110441e31c5e7a3d493290de2af206043b584a83f9",
          "sha1": "43a02808e4c31b1c8fe60fc7a9e7e69d79636d99",
          "md5": "c7466d738370c4b94e15a8274d73c8b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.10.1-sources.jar",
          "url": "media3-exoplayer-1.10.1-sources.jar",
          "size": 1218734,
          "sha512": "30a516278b1a7a55f300eab4692c181b52054715a33a1bcb17bae299bc0a053104f021986a10acbb0ea9e005fdc19a5a9532ac4704a8d1c97241cadb76543eee",
          "sha256": "68378d00a9c979bdf2a0e3141be6138928a570543d23fc815ba92dadba174e7c",
          "sha1": "e6a10a8bf457bf0d5ace5bfa6041d7ee25227f06",
          "md5": "ee1b7c4dfd4538de0a50b48c13445e08"
        }
      ]
    }
  ]
}
