{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-smoothstreaming",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.2.1.aar",
          "url": "media3-exoplayer-smoothstreaming-1.2.1.aar",
          "size": 50443,
          "sha512": "61f798b115c30aafa3306bcc1a2632e169a40c0218ce07fa841d88b1b8de86e9d08a28e2305baee62f40ea810ff5b4f9315277e512e7cb75a940662a46f2a0c3",
          "sha256": "ca943547a0c8e02e7b3e02640deb60f4ba84448e611ac18b0e67b47668f8bca5",
          "sha1": "d1e2609c60b38cbbad7e45bacf39eaf86921b8ed",
          "md5": "e1fd8f32722a3cfb67dd81c5e4c19cbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.2.1.aar",
          "url": "media3-exoplayer-smoothstreaming-1.2.1.aar",
          "size": 50443,
          "sha512": "61f798b115c30aafa3306bcc1a2632e169a40c0218ce07fa841d88b1b8de86e9d08a28e2305baee62f40ea810ff5b4f9315277e512e7cb75a940662a46f2a0c3",
          "sha256": "ca943547a0c8e02e7b3e02640deb60f4ba84448e611ac18b0e67b47668f8bca5",
          "sha1": "d1e2609c60b38cbbad7e45bacf39eaf86921b8ed",
          "md5": "e1fd8f32722a3cfb67dd81c5e4c19cbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.2.1-sources.jar",
          "url": "media3-exoplayer-smoothstreaming-1.2.1-sources.jar",
          "size": 30050,
          "sha512": "0d6c60119a77da3cbcdcc7f546a386ac25ee706682c802a288ae7d9e77e64fb061f4813444647396615af7d58360e0bdf500604d9b807a44c8efa9a1bac927ca",
          "sha256": "79038bbc5b0ca42f7f176d61a753baf6a2de9947b211c465ea8a797f70ef6bd3",
          "sha1": "4748c3fe7e866261ff79b7a3f503ec3e986209b6",
          "md5": "ef8b4ba4db4ce8f01e50a1d327f30fc3"
        }
      ]
    }
  ]
}
