{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-rtsp",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.3.0.aar",
          "url": "media3-exoplayer-rtsp-1.3.0.aar",
          "size": 154527,
          "sha512": "c80c822b69db98109c6533fa9cf4b5ae91eea19792487526e546b8dd172cfff638ab3fdf6b8678c5b776f91e88ce4c94aea535234f156b7518f4d99ba2c0a32c",
          "sha256": "71ba50c18fceccdc190185f249fd7dbe7eafe8ab3ed8641304a0b01a8e80bc16",
          "sha1": "6c37c7db90ca5117aeec84f6452c88a4b8793570",
          "md5": "19542554d957ab32f7e740e2dc68abb1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.3.0.aar",
          "url": "media3-exoplayer-rtsp-1.3.0.aar",
          "size": 154527,
          "sha512": "c80c822b69db98109c6533fa9cf4b5ae91eea19792487526e546b8dd172cfff638ab3fdf6b8678c5b776f91e88ce4c94aea535234f156b7518f4d99ba2c0a32c",
          "sha256": "71ba50c18fceccdc190185f249fd7dbe7eafe8ab3ed8641304a0b01a8e80bc16",
          "sha1": "6c37c7db90ca5117aeec84f6452c88a4b8793570",
          "md5": "19542554d957ab32f7e740e2dc68abb1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.3.0-sources.jar",
          "url": "media3-exoplayer-rtsp-1.3.0-sources.jar",
          "size": 119383,
          "sha512": "2e816bc039a0653c148aba7d0827d5e982a2abe8fa758b07cfda2ff0f4071b2dabc17a64a14790c6203fe7a2c301dc2c310aa380b1fdc6c27efa37e6fefb6e76",
          "sha256": "1c92d81b6da5bd6018b3082f0374c4fbf91459c7cbd9384511a2ba80c1767ff8",
          "sha1": "42ed81fd6ee64c6baa1d72b985022252959c1ee3",
          "md5": "c4c85d31e3d86fa77fb1ab8f454afaf4"
        }
      ]
    }
  ]
}
