{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-flac",
    "version": "1.11.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-flac-1.11.0-rc01.aar",
          "url": "media3-decoder-flac-1.11.0-rc01.aar",
          "size": 577144,
          "sha512": "154d694c9d92ebf873acd2ff165733fd20f143819298a6c0f48e227bb3b1205fd4386b932fe5b5fedc2f5ef615c9410f11243f2d464462843259acd5b9db496f",
          "sha256": "d31ced45900d7e42df4a40cab70407a6c7c8114880a4a0e69d3e1b8229caf990",
          "sha1": "f21fc98f25494c61d5627325df19577bea13c4bb",
          "md5": "c8be8e4cf9665b31784742219b24c3c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-flac-1.11.0-rc01.aar",
          "url": "media3-decoder-flac-1.11.0-rc01.aar",
          "size": 577144,
          "sha512": "154d694c9d92ebf873acd2ff165733fd20f143819298a6c0f48e227bb3b1205fd4386b932fe5b5fedc2f5ef615c9410f11243f2d464462843259acd5b9db496f",
          "sha256": "d31ced45900d7e42df4a40cab70407a6c7c8114880a4a0e69d3e1b8229caf990",
          "sha1": "f21fc98f25494c61d5627325df19577bea13c4bb",
          "md5": "c8be8e4cf9665b31784742219b24c3c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-flac-1.11.0-rc01-sources.jar",
          "url": "media3-decoder-flac-1.11.0-rc01-sources.jar",
          "size": 15816,
          "sha512": "5fc19a47c38fb87078b6400e8ec7c5630ac39b99c1e64cc0ee7e0311d4c8260d4bd4ee62b56a43fd7af125419e23fe09049ddb849c0cca70676c0ab436ae3cc1",
          "sha256": "485bd4625f81bae925b87e47b8ac8efc2d9f50c50d3f7b82adc05f55dab26e0e",
          "sha1": "2c4870a59c179542a2ec371649f978781800fcfc",
          "md5": "6a8fd1f393309e4695dff2d96e675c1c"
        }
      ]
    }
  ]
}
