{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-beta01.aar",
          "url": "media3-exoplayer-1.9.0-beta01.aar",
          "size": 1633659,
          "sha512": "532dd8993bcde63db4988ccd31413d870dbe8ec9d8b5522223cdc3fb533c4bea8d1fd3dc28aae077d01f46f6ec847dd5be7933f12083a4fbaa4dbedd1af8963e",
          "sha256": "8246b60fb93588eb025a17af7262aaa37843df82b3ea8dd27c03ee8aca3c7a7b",
          "sha1": "1fc22578bd76f32c37eb9ba893b9e19be61cbdf0",
          "md5": "9949fd8f3762be3ea8dd31c9b5e13936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-beta01.aar",
          "url": "media3-exoplayer-1.9.0-beta01.aar",
          "size": 1633659,
          "sha512": "532dd8993bcde63db4988ccd31413d870dbe8ec9d8b5522223cdc3fb533c4bea8d1fd3dc28aae077d01f46f6ec847dd5be7933f12083a4fbaa4dbedd1af8963e",
          "sha256": "8246b60fb93588eb025a17af7262aaa37843df82b3ea8dd27c03ee8aca3c7a7b",
          "sha1": "1fc22578bd76f32c37eb9ba893b9e19be61cbdf0",
          "md5": "9949fd8f3762be3ea8dd31c9b5e13936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-beta01-sources.jar",
          "url": "media3-exoplayer-1.9.0-beta01-sources.jar",
          "size": 1166513,
          "sha512": "d2c16bb270aa9fa6f027156f28f29a752739cebe3e60836a4ceabc68ab8d9d5d1d321ec56253f1de486ca6b926fb7e58a438f3d78dbea94591c5da7d92edbc30",
          "sha256": "ea3a32509e992dfa730654fbaf4ae36fad0e6fc4da3e506bb0bf59313ff0057e",
          "sha1": "9f3e036d67afca9edb37ad70d6b799112fa28409",
          "md5": "5cd390a355c04d6687babb800d8d14dc"
        }
      ]
    }
  ]
}
