{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-dash",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.4.0.aar",
          "url": "media3-exoplayer-dash-1.4.0.aar",
          "size": 139125,
          "sha512": "5498b6968e9d5ebf6aa253036e52b783a15fa9ea4d635271b64013aaf53b600472a826b54793a1269ad906ded13f2ea4f85c0bdcbd6250e737588c2cd66128e3",
          "sha256": "3940c66935d718d07abaae05b11ab89751b300b7cee4b8ada1ba9510e7362759",
          "sha1": "369f792b0dfa02d57f5c45e50eeea6e05540c0e5",
          "md5": "8dadaea91564b465a20030f2278c1236"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-dash-1.4.0.aar",
          "url": "media3-exoplayer-dash-1.4.0.aar",
          "size": 139125,
          "sha512": "5498b6968e9d5ebf6aa253036e52b783a15fa9ea4d635271b64013aaf53b600472a826b54793a1269ad906ded13f2ea4f85c0bdcbd6250e737588c2cd66128e3",
          "sha256": "3940c66935d718d07abaae05b11ab89751b300b7cee4b8ada1ba9510e7362759",
          "sha1": "369f792b0dfa02d57f5c45e50eeea6e05540c0e5",
          "md5": "8dadaea91564b465a20030f2278c1236"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.4.0-sources.jar",
          "url": "media3-exoplayer-dash-1.4.0-sources.jar",
          "size": 93723,
          "sha512": "7c15b034e89ca1fbfca51bb30c2a634c33f88e68acb02364a3f1811a6e23a25fd25f1c063c8a04c54d2a0b0b05cc44258c5c7aaab9e3b27ad44d2086a2aa9ec3",
          "sha256": "64417bdc5597043621ad689117b18f76515426c31bd6e0b4dd4815a47041565e",
          "sha1": "07e00a54cc348a8da6a1b0d621d324d4f1a2e3cc",
          "md5": "a07e5f43af4b6f77ada93ad26ebcd41f"
        }
      ]
    }
  ]
}
