{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.10.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.0-rc01.aar",
          "url": "media3-exoplayer-1.10.0-rc01.aar",
          "size": 1690649,
          "sha512": "9825fb2252edfdf746fe4ddfb55ccede09286cc2d1d953a422b0777e79a581d07868be7ecc5db08bf1fac147952427648fb87166d8ead2c03928fa300e087871",
          "sha256": "6528c170b32a63d133f8d4051bee6a24ecec5c4a252ed6165bfa7868caaf7c41",
          "sha1": "d0546b748c99e1722d54d3963eafbb1449706a06",
          "md5": "f44ad40c507c1ac5152deb44221a0910"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.0-rc01.aar",
          "url": "media3-exoplayer-1.10.0-rc01.aar",
          "size": 1690649,
          "sha512": "9825fb2252edfdf746fe4ddfb55ccede09286cc2d1d953a422b0777e79a581d07868be7ecc5db08bf1fac147952427648fb87166d8ead2c03928fa300e087871",
          "sha256": "6528c170b32a63d133f8d4051bee6a24ecec5c4a252ed6165bfa7868caaf7c41",
          "sha1": "d0546b748c99e1722d54d3963eafbb1449706a06",
          "md5": "f44ad40c507c1ac5152deb44221a0910"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.10.0-rc01-sources.jar",
          "url": "media3-exoplayer-1.10.0-rc01-sources.jar",
          "size": 1215429,
          "sha512": "6e7f88f82c613af8705cb068c7d3d9829b7e8196731d62d3b5c33fce6910d1bef4c97b9987250490a851ad62463133f92780c9d287be415fb13e6e0b255a8545",
          "sha256": "5879b65b708ce06ee06a0163e81843fcb8e9aff97ef095d6f0d6310e2bbb5722",
          "sha1": "72ad0b5f9124dbae378810dc5b086080ccd59de1",
          "md5": "a63ead8f25cb791a9e41c314140da147"
        }
      ]
    }
  ]
}
