{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource-okhttp",
    "version": "1.11.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0-rc01.aar",
          "url": "media3-datasource-okhttp-1.11.0-rc01.aar",
          "size": 9778,
          "sha512": "d957fc0a6914d842f36ab0c8ce0d55cd06d03ab80d076befe1830f6ea30e77773ce5eb48b18559e17d08149a2a24d4260c205a29851663ef2552f90ab4cd383a",
          "sha256": "b4577e49400c39f59820637c2ef25b764f1b2a1cf742c1cb703a29ca5a5e1996",
          "sha1": "c91456939f741acd46c855bc4b356e36696e4f1d",
          "md5": "e3391ec10345062853a91ca69e315d42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0-rc01.aar",
          "url": "media3-datasource-okhttp-1.11.0-rc01.aar",
          "size": 9778,
          "sha512": "d957fc0a6914d842f36ab0c8ce0d55cd06d03ab80d076befe1830f6ea30e77773ce5eb48b18559e17d08149a2a24d4260c205a29851663ef2552f90ab4cd383a",
          "sha256": "b4577e49400c39f59820637c2ef25b764f1b2a1cf742c1cb703a29ca5a5e1996",
          "sha1": "c91456939f741acd46c855bc4b356e36696e4f1d",
          "md5": "e3391ec10345062853a91ca69e315d42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0-rc01-sources.jar",
          "url": "media3-datasource-okhttp-1.11.0-rc01-sources.jar",
          "size": 6285,
          "sha512": "f7d8615b3f7a7cc9e0e3a11bd57142ec793a9e7175edccd569636b28f6fde826fd6beea7d69dba5bfc53473f2a8b2f85e1ce5df5c1a5e14079944d388b831a58",
          "sha256": "e90957224aa28b7602604a0a5543f36e81570ca952185a4ae5538aa430768cdc",
          "sha1": "57fe7ca60017aceb5ae2463ee519c267464cabae",
          "md5": "b79ac78703ae0b6fb52fdea35a18949f"
        }
      ]
    }
  ]
}
