{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-flac",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.9.1.aar",
          "url": "media3-decode-flac-1.9.1.aar",
          "size": 578699,
          "sha512": "b350e08accba3935e66d17acb638c1018408ce01c2b329755632c99c8773198ac056ac470ff8ddd761faa8ec4c2631c7bd84b0faf2ab7d56039815137be479fa",
          "sha256": "917c64a4975d58007a8187a4bb422555863b945dafa89fd160ced3064357f8c2",
          "sha1": "a90c5803e1ad320d0a1d22eef4dfdd90c5655718",
          "md5": "8db10979c9ef2c80147757390c45ae7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.9.1.aar",
          "url": "media3-decode-flac-1.9.1.aar",
          "size": 578699,
          "sha512": "b350e08accba3935e66d17acb638c1018408ce01c2b329755632c99c8773198ac056ac470ff8ddd761faa8ec4c2631c7bd84b0faf2ab7d56039815137be479fa",
          "sha256": "917c64a4975d58007a8187a4bb422555863b945dafa89fd160ced3064357f8c2",
          "sha1": "a90c5803e1ad320d0a1d22eef4dfdd90c5655718",
          "md5": "8db10979c9ef2c80147757390c45ae7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-flac-1.9.1-sources.jar",
          "url": "media3-decode-flac-1.9.1-sources.jar",
          "size": 15748,
          "sha512": "ace6d2a23a3ac31f89c72e99fa5e525e1dd02184583e2260ae39c102b8f3bbc891ae90e58e640e3e1a9bbc84511366521732ffe6edab21a47bb3ebc904e92e74",
          "sha256": "636547d168b74eb6dde49727aa1b5430eb79b5b86cc77808dd9aaa44dfa948dc",
          "sha1": "648f0d2d5ae45d632506a44abcc31d234c370b97",
          "md5": "26cc69a7600a7b8a9561233647815276"
        }
      ]
    }
  ]
}
