{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-test-utils",
    "version": "1.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.11.0-alpha01.aar",
          "url": "media3-test-utils-1.11.0-alpha01.aar",
          "size": 496420,
          "sha512": "d42615883482578a64946ab1d6501d9a1d53662a5aae076f524beae6eb4d3030db1e4186dbd03a6688f314420fbbc4748d35cad2407cf129d84663524df9ac3e",
          "sha256": "e219fbd54a33c3207a1d4194008dc28e7848e249da0c8804c227e3c8f30674f5",
          "sha1": "d741c6564b4e0861ccaac699dc7363d33f33a5fe",
          "md5": "143b56f137b2b762b88f2ba22eefabc1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.testparameterinjector",
          "module": "test-parameter-injector",
          "version": {
            "requires": "1.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.11.0-alpha01.aar",
          "url": "media3-test-utils-1.11.0-alpha01.aar",
          "size": 496420,
          "sha512": "d42615883482578a64946ab1d6501d9a1d53662a5aae076f524beae6eb4d3030db1e4186dbd03a6688f314420fbbc4748d35cad2407cf129d84663524df9ac3e",
          "sha256": "e219fbd54a33c3207a1d4194008dc28e7848e249da0c8804c227e3c8f30674f5",
          "sha1": "d741c6564b4e0861ccaac699dc7363d33f33a5fe",
          "md5": "143b56f137b2b762b88f2ba22eefabc1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-test-utils-1.11.0-alpha01-sources.jar",
          "url": "media3-test-utils-1.11.0-alpha01-sources.jar",
          "size": 264129,
          "sha512": "9f32885b97c1d1c2eafb76c54c55edc833efc0a4cdcca50aacbbe33ab870c6c62cf5354a335fba4c89abcdc059f0c44dc6fd802440081a0ab6d090656211c538",
          "sha256": "af7e8a06c8b11d511ae28dd1b3d792d34ba073a6f444d3fd07407859c16a3564",
          "sha1": "0942ca55adb1a24dfe7d17d416625cca46eedf80",
          "md5": "7b96431d8211dba10635e0cc37a890a8"
        }
      ]
    }
  ]
}
