{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.10.0-rc03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.0-rc03.aar",
          "url": "media3-exoplayer-1.10.0-rc03.aar",
          "size": 1690773,
          "sha512": "db98aa92ae51ac8f155a6296fbc82bf5f6da6c6fad57c5b78f282e6aaa7a3056236e8c64795ff53a2e7915b454903d2d0e11a052ece90fdab45d35908fdb0e67",
          "sha256": "6afea050866353a77e4612b5ac4e0ed68cb20c055a49c34f738bfd5455a44bcb",
          "sha1": "4f41f46fd5ce3aab13928c835d36cff4b889256e",
          "md5": "4c41813acb0d81f67e3892f572e9299b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.0-rc03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.10.0-rc03.aar",
          "url": "media3-exoplayer-1.10.0-rc03.aar",
          "size": 1690773,
          "sha512": "db98aa92ae51ac8f155a6296fbc82bf5f6da6c6fad57c5b78f282e6aaa7a3056236e8c64795ff53a2e7915b454903d2d0e11a052ece90fdab45d35908fdb0e67",
          "sha256": "6afea050866353a77e4612b5ac4e0ed68cb20c055a49c34f738bfd5455a44bcb",
          "sha1": "4f41f46fd5ce3aab13928c835d36cff4b889256e",
          "md5": "4c41813acb0d81f67e3892f572e9299b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.10.0-rc03-sources.jar",
          "url": "media3-exoplayer-1.10.0-rc03-sources.jar",
          "size": 1215574,
          "sha512": "c57b89ac062a401eeed1092ea72a877714e8991c6b0ec2bb2de935d30596f4769cefad39c1d0f6bd8b51eea3650cd1e1134738ac66050f150e94d3a27891b139",
          "sha256": "5c7a47e479f8f06e65397edd3c9a332d11849e24bd07b0011ec936d7d24d0730",
          "sha1": "e89e34ae71c33afc512523d629a6017c3fa7069f",
          "md5": "1ad83310fac875bca063bc21cd926b1e"
        }
      ]
    }
  ]
}
