{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.11.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.11.0-rc01.aar",
          "url": "media3-cast-1.11.0-rc01.aar",
          "size": 120431,
          "sha512": "4b8f17fcd0084c7bba1ec6155e9033308cb5a7827c3ae353121ba1f711e0ee9dfe2900f643e02a11f6bb3de8d84a00ec25ef76e1590114be1da8b9ca834f5a7f",
          "sha256": "a54dc7a31d33b40c4518ccf6802f42b37c518ecf341f40e1dc03bf6efcf6b35d",
          "sha1": "9a8bd6666ce3a794837ec3c1e74442239808b9ba",
          "md5": "fb7efb87f1c63c09c327e4e4b5e00c0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.11.0-rc01.aar",
          "url": "media3-cast-1.11.0-rc01.aar",
          "size": 120431,
          "sha512": "4b8f17fcd0084c7bba1ec6155e9033308cb5a7827c3ae353121ba1f711e0ee9dfe2900f643e02a11f6bb3de8d84a00ec25ef76e1590114be1da8b9ca834f5a7f",
          "sha256": "a54dc7a31d33b40c4518ccf6802f42b37c518ecf341f40e1dc03bf6efcf6b35d",
          "sha1": "9a8bd6666ce3a794837ec3c1e74442239808b9ba",
          "md5": "fb7efb87f1c63c09c327e4e4b5e00c0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.11.0-rc01-sources.jar",
          "url": "media3-cast-1.11.0-rc01-sources.jar",
          "size": 60617,
          "sha512": "5312e10920ab3be2f848ffd44a846573d0fd32aafc84d44fa62b8750a40be8fb48fe332847ee8241baed984469711a8cb34ecc2159331f602000566cc0ba2e5f",
          "sha256": "69cd3888caae063aff7c3857072e8bc1cd4f1ff14dd4b3477d5f10114888a96b",
          "sha1": "585e6521f913ad42a0fafdeae2cb18d1b0e2aaf8",
          "md5": "0e565e37ffd05b8a52b2fcec06b7682f"
        }
      ]
    }
  ]
}
