{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-midi",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-midi-1.10.0.aar",
          "url": "media3-exoplayer-midi-1.10.0.aar",
          "size": 269186,
          "sha512": "da4f0cabb6364672cd83d18462252a40a82c3aa7c06e37ea928ecd76a314c5ce959e16529aae1c1b5f0eb233031e3795c2b10a8d8c28d29bc665dde5b06f0ebc",
          "sha256": "87a0e304f70c4b0e9acf71f9e26db7a4ec874a4fd7dfc6160e7bf3f2c9398726",
          "sha1": "3bba9238e690e9f57d18c1f3ddb15a0428800168",
          "md5": "e8eeaa5896bc4f17434f032dc48d9ca0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.philburk",
          "module": "jsyn",
          "version": {
            "requires": "3f6b44b853bccc0d2e3027104d575fcc5ccb6d4e"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-midi-1.10.0.aar",
          "url": "media3-exoplayer-midi-1.10.0.aar",
          "size": 269186,
          "sha512": "da4f0cabb6364672cd83d18462252a40a82c3aa7c06e37ea928ecd76a314c5ce959e16529aae1c1b5f0eb233031e3795c2b10a8d8c28d29bc665dde5b06f0ebc",
          "sha256": "87a0e304f70c4b0e9acf71f9e26db7a4ec874a4fd7dfc6160e7bf3f2c9398726",
          "sha1": "3bba9238e690e9f57d18c1f3ddb15a0428800168",
          "md5": "e8eeaa5896bc4f17434f032dc48d9ca0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-midi-1.10.0-sources.jar",
          "url": "media3-exoplayer-midi-1.10.0-sources.jar",
          "size": 35031,
          "sha512": "82d7ffaa92803bc552ceda7133ef1c9e0b731522e33cb23a4ba029c6e82c8fc9bad31cb0b9a69c3187f7779d0cbbfcf45ceafd1170b1cc7d3f1664017001f7eb",
          "sha256": "aa8e634c056e92fe02d91450a61f8581c30a732ddbea5da33de3332ce993b7b1",
          "sha1": "1e9de27757e7d8f242e77deb7d31db6bb046f8a3",
          "md5": "c56eda58c73f3a2c7a6ca68dc0ff78bd"
        }
      ]
    }
  ]
}
