{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-test-utils",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.truth.extensions",
          "module": "truth-java8-extension",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.10.0-alpha01.aar",
          "url": "media3-test-utils-1.10.0-alpha01.aar",
          "size": 421329,
          "sha512": "32916f8272ff30a5f91433a365a3d03d9e448b403aa672db2e08b154b2055944856c777e1c44d98964821f83d19f20a80e1ae28d956ce7384b8763748954a9f7",
          "sha256": "5c493a5843a04bfda996e001a3c9dac9d14780c48f82bbb676140cb931ced19f",
          "sha1": "15fc50683b1b4df6bb7fe68611cfca7738fa896d",
          "md5": "267a4e498a17358b159bc8c86f9bcbf0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.testparameterinjector",
          "module": "test-parameter-injector",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.12.4"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.truth.extensions",
          "module": "truth-java8-extension",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-test-utils-1.10.0-alpha01.aar",
          "url": "media3-test-utils-1.10.0-alpha01.aar",
          "size": 421329,
          "sha512": "32916f8272ff30a5f91433a365a3d03d9e448b403aa672db2e08b154b2055944856c777e1c44d98964821f83d19f20a80e1ae28d956ce7384b8763748954a9f7",
          "sha256": "5c493a5843a04bfda996e001a3c9dac9d14780c48f82bbb676140cb931ced19f",
          "sha1": "15fc50683b1b4df6bb7fe68611cfca7738fa896d",
          "md5": "267a4e498a17358b159bc8c86f9bcbf0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-test-utils-1.10.0-alpha01-sources.jar",
          "url": "media3-test-utils-1.10.0-alpha01-sources.jar",
          "size": 238623,
          "sha512": "e4ebcbca96e4f6df69bca9a6eb5abe071d554c3c915b51bdbab2960d8620fdc2b475b0418074e74ef850f8ae345a999f387c04bb096db866edd662119da46ae9",
          "sha256": "f10ff379a556bf1a71bcbb32edcd3432446b25e409ee9be051384a2e45a50e16",
          "sha1": "8992debfcb85f3699530109d152ea51e397b9c12",
          "md5": "f72f9b572a27ad3ea5bb600ed30640f3"
        }
      ]
    }
  ]
}
