{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-effect",
    "version": "1.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.11.0-alpha01.aar",
          "url": "media3-effect-1.11.0-alpha01.aar",
          "size": 419212,
          "sha512": "979b83c7674668e5fa41fed8e7190c55831e237567e9627d77a4fa33ff5609caf11fecef9e4b1a36a6cb3d6af0470e449f469a4b98949c0c7b70d12b030b8e5b",
          "sha256": "41e33ce474b660d4ae18e8b3849da70e883c5b838bfdd061124e9c1e795e533b",
          "sha1": "4f444fbe1f5b878e2f7d491fd41a4b6be5a5b7a3",
          "md5": "a02c625030e54e9af4f3a7a8dd368872"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.11.0-alpha01.aar",
          "url": "media3-effect-1.11.0-alpha01.aar",
          "size": 419212,
          "sha512": "979b83c7674668e5fa41fed8e7190c55831e237567e9627d77a4fa33ff5609caf11fecef9e4b1a36a6cb3d6af0470e449f469a4b98949c0c7b70d12b030b8e5b",
          "sha256": "41e33ce474b660d4ae18e8b3849da70e883c5b838bfdd061124e9c1e795e533b",
          "sha1": "4f444fbe1f5b878e2f7d491fd41a4b6be5a5b7a3",
          "md5": "a02c625030e54e9af4f3a7a8dd368872"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-effect-1.11.0-alpha01-sources.jar",
          "url": "media3-effect-1.11.0-alpha01-sources.jar",
          "size": 249361,
          "sha512": "7832518aa6cdecf2eaf8282c28d270c9bfcaaf65be253672e734ffbb03ade25c7e7624eafe5c91cb454951417d799ab1ebd470f442ff02f035ffa0945d204942",
          "sha256": "46813836d49a756b4ef7ad09ad5ad28eddbde3243ca9cf2c8befebe5ab280fca",
          "sha1": "35e06b293662fb276f235a7ce60f946dba1c66e5",
          "md5": "cc1a4fdbcbc9ab0fed4a9cf2d76de7c8"
        }
      ]
    }
  ]
}
