{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-ima",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.39.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.10.1.aar",
          "url": "media3-exoplayer-ima-1.10.1.aar",
          "size": 92868,
          "sha512": "48ce50d10f341f825bb1f3a27fc27262bf5b4796e6bb94ff42a76b600350b90f0b01a90b0add822b533822c6ab80c59fd83264875db3e3cc125091d013c010ae",
          "sha256": "ebcedf105b2bdcedabf77387c1e40e733dbc6b3445723a2b6d77437db8c51dd2",
          "sha1": "d7326e7e037c5c8d13dc6e9e1572223d9b368478",
          "md5": "fdfe2f338e27312c3fd2ec8eca23d5d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.39.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.10.1.aar",
          "url": "media3-exoplayer-ima-1.10.1.aar",
          "size": 92868,
          "sha512": "48ce50d10f341f825bb1f3a27fc27262bf5b4796e6bb94ff42a76b600350b90f0b01a90b0add822b533822c6ab80c59fd83264875db3e3cc125091d013c010ae",
          "sha256": "ebcedf105b2bdcedabf77387c1e40e733dbc6b3445723a2b6d77437db8c51dd2",
          "sha1": "d7326e7e037c5c8d13dc6e9e1572223d9b368478",
          "md5": "fdfe2f338e27312c3fd2ec8eca23d5d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-ima-1.10.1-sources.jar",
          "url": "media3-exoplayer-ima-1.10.1-sources.jar",
          "size": 53510,
          "sha512": "5049206bc794a878c056e8203dd9cf7bdbac42d39bcd7229d634c895a8f61f0ac6c6e4ec3fbc5b30709a2188108fe07f32fc4bbe14c2f0215ffd47eeb6a73039",
          "sha256": "98e53d3114f75baa2c0e38baaba05eac0426e72e41de32a0f179a827722d87f0",
          "sha1": "016e423915b356903884efd3aa5e4908b9b7ab64",
          "md5": "7a8d26b959b80389939688dc3a7b1137"
        }
      ]
    }
  ]
}
