{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0.aar",
          "url": "media3-decode-av1-1.10.0.aar",
          "size": 2178355,
          "sha512": "228c16119854c0436f03bae4c929b584b844d67dfa3d9689a3afcd0187da8254201a31d8417d51da933042f32dc267c7677149fbd4f9c7c742a321b6895038d1",
          "sha256": "b96fc180afb8e095efede44c22ec97014e8f24b718f176c01e17dd579ce98265",
          "sha1": "bb20d8c0944df3e46d4b2f76e5afcead6c3f7198",
          "md5": "972f40883fb17454cd6761752d7535d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0.aar",
          "url": "media3-decode-av1-1.10.0.aar",
          "size": 2178355,
          "sha512": "228c16119854c0436f03bae4c929b584b844d67dfa3d9689a3afcd0187da8254201a31d8417d51da933042f32dc267c7677149fbd4f9c7c742a321b6895038d1",
          "sha256": "b96fc180afb8e095efede44c22ec97014e8f24b718f176c01e17dd579ce98265",
          "sha1": "bb20d8c0944df3e46d4b2f76e5afcead6c3f7198",
          "md5": "972f40883fb17454cd6761752d7535d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-sources.jar",
          "url": "media3-decode-av1-1.10.0-sources.jar",
          "size": 10338,
          "sha512": "53ba0e3a58acbb3d5e1c8766e58e0f72787fe6b1ab8371bfaa0bc81867269d7f573a4107f7cf576c07d00efe3fe4118de3654ae3526c5196f88d19e8dbbf2f0a",
          "sha256": "33284308e55d631071ec2834f84b195500a44fe7a6c9d13dd4d0f8ef11614e0c",
          "sha1": "df9b55fd0d6c081747562a24ba91e1711ffa94c2",
          "md5": "e9f6077c1100cd645389b9dfe841d5c0"
        }
      ]
    }
  ]
}
