{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-ffmpeg",
    "version": "1.8.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.8.0-rc01.aar",
          "url": "media3-decode-ffmpeg-1.8.0-rc01.aar",
          "size": 3357104,
          "sha512": "c38fa2bfd4a4eb67193a1c7db71e774b1a58f9a1928bc2e0e15fa743d7eef4495fbf9f7c86aedadf5d8ff9ffa2900af0faa364ccf78b493c22afcf4e5fd3aa65",
          "sha256": "1d3729fa896f6a09ef6aacf2ee73f75f03bc0b59ac24341811bbf45bbd48c4db",
          "sha1": "1f7e080949a9ebaf78f426263db4067c7020b122",
          "md5": "28e406f04a433a6088cf32bdaec93edb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.8.0-rc01.aar",
          "url": "media3-decode-ffmpeg-1.8.0-rc01.aar",
          "size": 3357104,
          "sha512": "c38fa2bfd4a4eb67193a1c7db71e774b1a58f9a1928bc2e0e15fa743d7eef4495fbf9f7c86aedadf5d8ff9ffa2900af0faa364ccf78b493c22afcf4e5fd3aa65",
          "sha256": "1d3729fa896f6a09ef6aacf2ee73f75f03bc0b59ac24341811bbf45bbd48c4db",
          "sha1": "1f7e080949a9ebaf78f426263db4067c7020b122",
          "md5": "28e406f04a433a6088cf32bdaec93edb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-ffmpeg-1.8.0-rc01-sources.jar",
          "url": "media3-decode-ffmpeg-1.8.0-rc01-sources.jar",
          "size": 11541,
          "sha512": "c5e4a8943d587b09f61987d9a1e654186f6b61264ad8eb205a3f1a414162960a817e7a10c2cdb7b2f193cb0e9aff3927456f628d7b38dcc6f929cec902bbd40c",
          "sha256": "cc60f0856dd96c505e713042ede46b5df275556a27e6e4ac22d1427907e798e7",
          "sha1": "3b44c209b2917c428fe8fc63f9d7d48657ca8023",
          "md5": "f86383552b27500b817c1731bbb539c9"
        }
      ]
    }
  ]
}
