{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.10.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.10.0-beta01.aar",
          "url": "media3-common-1.10.0-beta01.aar",
          "size": 605984,
          "sha512": "ddec945b35f0c19a4c19e461a7fc7d0aba0094b1a31856896dbb4c992c0f43c90ab75a34eaad24b26089893e3bc9abe0acad08a9c703492d0aebbb70ced7fc92",
          "sha256": "5842f1daa9c48cf4ffb7fe7709c49340bc7664136c307866bd9e29b850daa44f",
          "sha1": "3b6d82ad92e82459affc6649b4c1f899c9ab9e01",
          "md5": "bb66ae04b7847cac8829c73eda6e9e64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-av1",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-ffmpeg",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-flac",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-iamf",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-opus",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-vp9",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect-lottie",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector-frame",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.10.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.10.0-beta01.aar",
          "url": "media3-common-1.10.0-beta01.aar",
          "size": 605984,
          "sha512": "ddec945b35f0c19a4c19e461a7fc7d0aba0094b1a31856896dbb4c992c0f43c90ab75a34eaad24b26089893e3bc9abe0acad08a9c703492d0aebbb70ced7fc92",
          "sha256": "5842f1daa9c48cf4ffb7fe7709c49340bc7664136c307866bd9e29b850daa44f",
          "sha1": "3b6d82ad92e82459affc6649b4c1f899c9ab9e01",
          "md5": "bb66ae04b7847cac8829c73eda6e9e64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.10.0-beta01-sources.jar",
          "url": "media3-common-1.10.0-beta01-sources.jar",
          "size": 491910,
          "sha512": "4ac131d84efd2c98c7d9a7d25f87ed63614554fb6c32aee018286a02d9edc6493fe77f1f55062f28db2848259715f6fc9a9f2e69124f3cc589d6731bcd09f2f0",
          "sha256": "964580cd9f9cfc42923a1eb2fa43ee24f52c7896bf90ef9c70ef83446ddc2b36",
          "sha1": "39d7d006d27511a7f1034562e5a4723b77e63d82",
          "md5": "5adf4c72c20630a36f96c5aefd3e9cd5"
        }
      ]
    }
  ]
}
