{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.9.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.9.0-rc01.aar",
          "url": "media3-decode-av1-1.9.0-rc01.aar",
          "size": 2178499,
          "sha512": "57ed6226bb99530474aa37e72b810b26e2c0b31f7b81be78dedd9da6d7e1140c7a819bc8d47fad4fb41fe11d2610c23d63616948baa208c62942edb382997a29",
          "sha256": "ca1481f2a369985e5be34e6f4426cf9fcd465bf578e1c846adfb5dd94ffbd21b",
          "sha1": "432507ef2f789ea20b0f2024186981eab013e610",
          "md5": "2297191981d39787db61b2475a67b4c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.9.0-rc01.aar",
          "url": "media3-decode-av1-1.9.0-rc01.aar",
          "size": 2178499,
          "sha512": "57ed6226bb99530474aa37e72b810b26e2c0b31f7b81be78dedd9da6d7e1140c7a819bc8d47fad4fb41fe11d2610c23d63616948baa208c62942edb382997a29",
          "sha256": "ca1481f2a369985e5be34e6f4426cf9fcd465bf578e1c846adfb5dd94ffbd21b",
          "sha1": "432507ef2f789ea20b0f2024186981eab013e610",
          "md5": "2297191981d39787db61b2475a67b4c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.9.0-rc01-sources.jar",
          "url": "media3-decode-av1-1.9.0-rc01-sources.jar",
          "size": 10338,
          "sha512": "53ba0e3a58acbb3d5e1c8766e58e0f72787fe6b1ab8371bfaa0bc81867269d7f573a4107f7cf576c07d00efe3fe4118de3654ae3526c5196f88d19e8dbbf2f0a",
          "sha256": "33284308e55d631071ec2834f84b195500a44fe7a6c9d13dd4d0f8ef11614e0c",
          "sha1": "df9b55fd0d6c081747562a24ba91e1711ffa94c2",
          "md5": "e9f6077c1100cd645389b9dfe841d5c0"
        }
      ]
    }
  ]
}
