{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-hls",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.4.0.aar",
          "url": "media3-exoplayer-hls-1.4.0.aar",
          "size": 167058,
          "sha512": "52318cc3df7471c5f45c537af6c2ad869dbe3f43cb7ac2149f0213e864b5d41e4391474c701992466c8642143b1f3a90320c57f85e8bc52cfa06076f851f80e5",
          "sha256": "43546b6b2ef0c2816f5d3af181c2179a5c1bddb9df85b7b84b3428cd37c887de",
          "sha1": "8d73b9a793d6fec027ca97ad0711e3afd501d40f",
          "md5": "425e2971cc094d4ab0248aa48be9362c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.4.0.aar",
          "url": "media3-exoplayer-hls-1.4.0.aar",
          "size": 167058,
          "sha512": "52318cc3df7471c5f45c537af6c2ad869dbe3f43cb7ac2149f0213e864b5d41e4391474c701992466c8642143b1f3a90320c57f85e8bc52cfa06076f851f80e5",
          "sha256": "43546b6b2ef0c2816f5d3af181c2179a5c1bddb9df85b7b84b3428cd37c887de",
          "sha1": "8d73b9a793d6fec027ca97ad0711e3afd501d40f",
          "md5": "425e2971cc094d4ab0248aa48be9362c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.4.0-sources.jar",
          "url": "media3-exoplayer-hls-1.4.0-sources.jar",
          "size": 122338,
          "sha512": "882dee9e1333015f64fe952708dc886990249e0c9fc8efcab3e69519dc4fb6b945e4d3438c78578a4da58f73cbcd9980bb39fcfc6bc178eb643e0deefa205c84",
          "sha256": "ecffc609b7e11875d4b3c5a6efb3f33a9d609de76430c9355334022f6bcc65cd",
          "sha1": "7e2bcf5e7c23f09f1afc66ecd2a5bf8f2def0003",
          "md5": "a9199d416bf82f4f120ea106534efed2"
        }
      ]
    }
  ]
}
