{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.10.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-rc01.aar",
          "url": "media3-decode-av1-1.10.0-rc01.aar",
          "size": 2178389,
          "sha512": "164cd932958cc96d9dc9506533a725042e9fe2d1c908ef164ba3f7320ee234b2fdbec1a542e956275ab308a4b078b7176a0d087e095615d2b6cf5a37fe534b3c",
          "sha256": "a034931106dbce100b44061ecff77bcb71a2362f58aaf67983e87cf42aeb82a6",
          "sha1": "07607ba28b4aa099e3f275d83a9c7727224c9466",
          "md5": "e6e83ea33caf9752f859405efcdd8d09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-rc01.aar",
          "url": "media3-decode-av1-1.10.0-rc01.aar",
          "size": 2178389,
          "sha512": "164cd932958cc96d9dc9506533a725042e9fe2d1c908ef164ba3f7320ee234b2fdbec1a542e956275ab308a4b078b7176a0d087e095615d2b6cf5a37fe534b3c",
          "sha256": "a034931106dbce100b44061ecff77bcb71a2362f58aaf67983e87cf42aeb82a6",
          "sha1": "07607ba28b4aa099e3f275d83a9c7727224c9466",
          "md5": "e6e83ea33caf9752f859405efcdd8d09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-rc01-sources.jar",
          "url": "media3-decode-av1-1.10.0-rc01-sources.jar",
          "size": 10338,
          "sha512": "53ba0e3a58acbb3d5e1c8766e58e0f72787fe6b1ab8371bfaa0bc81867269d7f573a4107f7cf576c07d00efe3fe4118de3654ae3526c5196f88d19e8dbbf2f0a",
          "sha256": "33284308e55d631071ec2834f84b195500a44fe7a6c9d13dd4d0f8ef11614e0c",
          "sha1": "df9b55fd0d6c081747562a24ba91e1711ffa94c2",
          "md5": "e9f6077c1100cd645389b9dfe841d5c0"
        }
      ]
    }
  ]
}
