{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-database",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-database-1.4.0.aar",
          "url": "media3-database-1.4.0.aar",
          "size": 7196,
          "sha512": "d3815836a679525a879497947a16fdad8ae71d5c2c22a9c41e78fd8114844c9a6cb27e518cb74ae29b7b8648e6021f1562b747d0bbc08445192e12d413146efd",
          "sha256": "2170ae6448cd499fc570dafa81e5687ad813995b7c2b7ff6801acaaa9a88bb4a",
          "sha1": "2000ab8702e42ae279cbc331e4cbb3fa84b7477f",
          "md5": "99f2b1f94593cc59e1045df545298f69"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-database-1.4.0.aar",
          "url": "media3-database-1.4.0.aar",
          "size": 7196,
          "sha512": "d3815836a679525a879497947a16fdad8ae71d5c2c22a9c41e78fd8114844c9a6cb27e518cb74ae29b7b8648e6021f1562b747d0bbc08445192e12d413146efd",
          "sha256": "2170ae6448cd499fc570dafa81e5687ad813995b7c2b7ff6801acaaa9a88bb4a",
          "sha1": "2000ab8702e42ae279cbc331e4cbb3fa84b7477f",
          "md5": "99f2b1f94593cc59e1045df545298f69"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-database-1.4.0-sources.jar",
          "url": "media3-database-1.4.0-sources.jar",
          "size": 8391,
          "sha512": "5de040766ed9bdddf3e551b903f49c09c2bfecb2330c9e78a249b9d86f1cef5cba5582a9f10098f72c7adf7e786d6fdd1154521f74dc8a35d3a528c03aab7086",
          "sha256": "1baca4ff0a32e76d08b92ed5d33e0278aa34a9e9c537edbc2fd39573e8ec46a3",
          "sha1": "b8a91c32c00129b65c8cc9148201632b27c4a240",
          "md5": "b509a427e0eee1b73f1710b698bdcd9e"
        }
      ]
    }
  ]
}
