{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-iamf",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0.aar",
          "url": "media3-decode-iamf-1.10.0.aar",
          "size": 11957831,
          "sha512": "69c51673609686bd4c50f86b6482de9675e237517ee3352261128f497a572f66e605e8400ebeb8b13170c149fdfc4198c698ddfd445607a6920468313d93f448",
          "sha256": "cc822394df2c753058df55ee92e713e8cf357139e0726fc17df9ab8f4a1291fd",
          "sha1": "53434da3f5150dd0b420310be94997097f4469d4",
          "md5": "d91ab1c607373b0fbc8d31a78396aeb8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0.aar",
          "url": "media3-decode-iamf-1.10.0.aar",
          "size": 11957831,
          "sha512": "69c51673609686bd4c50f86b6482de9675e237517ee3352261128f497a572f66e605e8400ebeb8b13170c149fdfc4198c698ddfd445607a6920468313d93f448",
          "sha256": "cc822394df2c753058df55ee92e713e8cf357139e0726fc17df9ab8f4a1291fd",
          "sha1": "53434da3f5150dd0b420310be94997097f4469d4",
          "md5": "d91ab1c607373b0fbc8d31a78396aeb8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0-sources.jar",
          "url": "media3-decode-iamf-1.10.0-sources.jar",
          "size": 10272,
          "sha512": "87a2f249be87db69ea205f7ade2ae7679b7692a30e9dd0b502d5469c124de88bb3c0a68d815b449bd8af36cf945817be13fdc41c891725e3ee93906754346002",
          "sha256": "cdb22503a1506ae59b5d17f6129b08f42aa5085127b02c25d09ea264e57ad47e",
          "sha1": "634607c02ce0bfba6543a372dc6584b516cf4ab4",
          "md5": "539132c136a87cb5c9df6255e8309116"
        }
      ]
    }
  ]
}
