{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui-compose-material3",
    "version": "1.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-material3-1.9.0-beta01.aar",
          "url": "media3-ui-compose-material3-1.9.0-beta01.aar",
          "size": 257517,
          "sha512": "5a9a609330f65073385cccc3ec741b9f4fce486fbd97722dd03b69cd1cfd3480124b879f610612f5278e2a3c28f60e3e169ae81066843994949571f550a636be",
          "sha256": "2ebe33a8058922c4612dc7e2c35c821b16067dc0ac10ef45eceb02656627c603",
          "sha1": "47044156af4231964ac69c8041c92c69dfdec6b4",
          "md5": "4feabbd35587a4328aaa3f50443db559"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-compose-material3-1.9.0-beta01.aar",
          "url": "media3-ui-compose-material3-1.9.0-beta01.aar",
          "size": 257517,
          "sha512": "5a9a609330f65073385cccc3ec741b9f4fce486fbd97722dd03b69cd1cfd3480124b879f610612f5278e2a3c28f60e3e169ae81066843994949571f550a636be",
          "sha256": "2ebe33a8058922c4612dc7e2c35c821b16067dc0ac10ef45eceb02656627c603",
          "sha1": "47044156af4231964ac69c8041c92c69dfdec6b4",
          "md5": "4feabbd35587a4328aaa3f50443db559"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-compose-material3-1.9.0-beta01-sources.jar",
          "url": "media3-ui-compose-material3-1.9.0-beta01-sources.jar",
          "size": 19439,
          "sha512": "f3b0e83c5cb4a6d0b8c6e73acd65a2862620829012a1d62d0f5bd05ad3e7f8fc2d16ed5f3af23fde67503a0cc6064273f279abd45ac94306099cdfcaa2f3f654",
          "sha256": "0e960e92d6559dd966cebe0bbfc66195ef9187c3ad99d1656d3fb77842cd5333",
          "sha1": "7549c06385dda85abab1f69196827bf933ea9bc3",
          "md5": "4326667efdc0f483e58abd93cb351880"
        }
      ]
    }
  ]
}
