{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-effect",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.10.0.aar",
          "url": "media3-effect-1.10.0.aar",
          "size": 414562,
          "sha512": "a4577bddbda7fb9c5452e44f153ea45dcb0c9719515c7f72e2fec512cb54b6ccffe1b4e1522dcbfe7807292eec05316487e72d76a0a74ad74e2b50a1c9e87ad3",
          "sha256": "7257915556a9ee1eaa24e8deaf5bd91fe3077e2dc3040f87beaf146854948235",
          "sha1": "c672ea62bc26cb5fa8489c47438af754b3405ff2",
          "md5": "2d5e78c42219c83ea8425f38b3c27b0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.10.0.aar",
          "url": "media3-effect-1.10.0.aar",
          "size": 414562,
          "sha512": "a4577bddbda7fb9c5452e44f153ea45dcb0c9719515c7f72e2fec512cb54b6ccffe1b4e1522dcbfe7807292eec05316487e72d76a0a74ad74e2b50a1c9e87ad3",
          "sha256": "7257915556a9ee1eaa24e8deaf5bd91fe3077e2dc3040f87beaf146854948235",
          "sha1": "c672ea62bc26cb5fa8489c47438af754b3405ff2",
          "md5": "2d5e78c42219c83ea8425f38b3c27b0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-effect-1.10.0-sources.jar",
          "url": "media3-effect-1.10.0-sources.jar",
          "size": 247743,
          "sha512": "6756b87980378c730902f201980a55c7c0b8997ffe11c6cccc122d1b8d65fb422d810064446162d5c0b79482709dc87a46cd5dfd90a71222457cf6d09a8ec06a",
          "sha256": "462e7af84f1349fc3c1871e302288278d5b0e4b6b83d9afcf7e26286cdc2d623",
          "sha1": "f348ba2347ac291aab143573734b893b861ee60d",
          "md5": "58ff66572cba356bd9d331e88a6cd00e"
        }
      ]
    }
  ]
}
