{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.9.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.9.0-rc01.aar",
          "url": "media3-common-1.9.0-rc01.aar",
          "size": 588184,
          "sha512": "6859c6f27874f0d884b49d77406f78b147cd73db65abb63d2b63635f6b57c07f1950df94fa9a78abd6806362a2758360350edb59f73498b2a45548005b2b585f",
          "sha256": "a0c91da379d7cbf41318a5cd798a96e036554cb557f63e190d5e3ff56cb57d1b",
          "sha1": "d179b018b726096cbcffdb3640ab9c26996eaa55",
          "md5": "caf5de6b80489668e7a7187e4aeb4ddf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-av1",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-ffmpeg",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-flac",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-iamf",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-opus",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decode-vp9",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.9.0-rc01.aar",
          "url": "media3-common-1.9.0-rc01.aar",
          "size": 588184,
          "sha512": "6859c6f27874f0d884b49d77406f78b147cd73db65abb63d2b63635f6b57c07f1950df94fa9a78abd6806362a2758360350edb59f73498b2a45548005b2b585f",
          "sha256": "a0c91da379d7cbf41318a5cd798a96e036554cb557f63e190d5e3ff56cb57d1b",
          "sha1": "d179b018b726096cbcffdb3640ab9c26996eaa55",
          "md5": "caf5de6b80489668e7a7187e4aeb4ddf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.9.0-rc01-sources.jar",
          "url": "media3-common-1.9.0-rc01-sources.jar",
          "size": 479705,
          "sha512": "d9a307247cb502a65c05c3a77d13b4be88dfe32aea48736e621852bcbd5cc205544a90ea0e1ced61731aee74b0b8283e030307e994b841a905b5efc0fddf1e32",
          "sha256": "d9dbc405178bb3dd860433052c47c91d8f09ac6164480316aeef965d70fa8bfd",
          "sha1": "5226da6896fdb577d504825ed7090a7c62e8fd3f",
          "md5": "d9201f90c400a8dd97073ef613ff5bfb"
        }
      ]
    }
  ]
}
