{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-vp9",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.9.0.aar",
          "url": "media3-decode-vp9-1.9.0.aar",
          "size": 9497,
          "sha512": "b8b863c15c0ac4a696e6b712aad19586562b8698eacf121bcd9db24a02a045e811c47f1ca9c0d4520c80145478630d7d26f1c9f14f6f71ae74d2aede82320d99",
          "sha256": "65676b2dfe7d53ea008cef3c1ec8f3508c833237fa0a05f6ebbe87afb2d42d3d",
          "sha1": "fdf98695b7797c1a2929991bba16607882e100cb",
          "md5": "744fd1ea8652f63d115b7cc1ec6cb113"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.9.0.aar",
          "url": "media3-decode-vp9-1.9.0.aar",
          "size": 9497,
          "sha512": "b8b863c15c0ac4a696e6b712aad19586562b8698eacf121bcd9db24a02a045e811c47f1ca9c0d4520c80145478630d7d26f1c9f14f6f71ae74d2aede82320d99",
          "sha256": "65676b2dfe7d53ea008cef3c1ec8f3508c833237fa0a05f6ebbe87afb2d42d3d",
          "sha1": "fdf98695b7797c1a2929991bba16607882e100cb",
          "md5": "744fd1ea8652f63d115b7cc1ec6cb113"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-vp9-1.9.0-sources.jar",
          "url": "media3-decode-vp9-1.9.0-sources.jar",
          "size": 8822,
          "sha512": "2594374f2ed77364c504b71343975dba4f6c2daee36f0e1dc60f62097c2fc433df8331a3c567165c5e42582ce331ac979f9ec9f7c0182d89f4be431fd28eeb8d",
          "sha256": "c9deea7e0fbbec2dc0f87e72de5b2147e6cf0bbdb20775d675cd114b13239ef9",
          "sha1": "145477e206abb0e68bbaf2bf4bf252e1b65a5908",
          "md5": "48373cf213bb108a2d150844b15fd69a"
        }
      ]
    }
  ]
}
