{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-midi",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-midi-1.4.0.aar",
          "url": "media3-exoplayer-midi-1.4.0.aar",
          "size": 270833,
          "sha512": "19bf68f0f936aa5dc77f5a61b2d10cf83cda96276511d9bd9332f39449182f10c806fcbe05cc7e0ac2ba6f0caaf1abb6d53ad57b23a76d262957af3bbe33ed3e",
          "sha256": "cdb30b7aeaf7f9600d497f4e31569f3ce2c183bde82af681fd5cb3953ba0c172",
          "sha1": "d4869155d434a6255f6f9e9d28d566d2ceffe027",
          "md5": "0a826c342abd4f90daeb57a6da4d8cf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.philburk",
          "module": "jsyn",
          "version": {
            "requires": "40a41092cbab558d7d410ec43d93bb1e4121e86a"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-midi-1.4.0.aar",
          "url": "media3-exoplayer-midi-1.4.0.aar",
          "size": 270833,
          "sha512": "19bf68f0f936aa5dc77f5a61b2d10cf83cda96276511d9bd9332f39449182f10c806fcbe05cc7e0ac2ba6f0caaf1abb6d53ad57b23a76d262957af3bbe33ed3e",
          "sha256": "cdb30b7aeaf7f9600d497f4e31569f3ce2c183bde82af681fd5cb3953ba0c172",
          "sha1": "d4869155d434a6255f6f9e9d28d566d2ceffe027",
          "md5": "0a826c342abd4f90daeb57a6da4d8cf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-midi-1.4.0-sources.jar",
          "url": "media3-exoplayer-midi-1.4.0-sources.jar",
          "size": 34987,
          "sha512": "035e05c658739799c1b9f38877cff1eb24937fe3a76bb75cb4bb010821f48c595ccfe5abc67422fc6fce53b37948e6c6f00fc3d1c48bb1bc1bb73bee2660de2b",
          "sha256": "3185ab9d9d00413fee01b0272a8ac3f4a2fb8e86b0bba5c9944050169b0cb636",
          "sha1": "3e436c4aea2a72863430b4d0611c32ac8ce6165c",
          "md5": "de3595fc982684b35eb2a658fedf5fde"
        }
      ]
    }
  ]
}
