{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-container",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.10.0.aar",
          "url": "media3-container-1.10.0.aar",
          "size": 58202,
          "sha512": "635cb3197e9c967c91b89a1a54e2fa983a0a2f9de9d603d2b2454b0dc5d6887db7c1a61b34c6ab890fff1b4f5d7c27f8abe3ae7b45845fa73ae492a3fbf07296",
          "sha256": "f4b42246885fdfc30e2de8bedb389ce00bc0322d6925c376655697e60d502065",
          "sha1": "6551ad96f3a1ee13724c61603ffa1c499adf8df5",
          "md5": "3813eefa7ca0b2e295482e17bc403438"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.10.0.aar",
          "url": "media3-container-1.10.0.aar",
          "size": 58202,
          "sha512": "635cb3197e9c967c91b89a1a54e2fa983a0a2f9de9d603d2b2454b0dc5d6887db7c1a61b34c6ab890fff1b4f5d7c27f8abe3ae7b45845fa73ae492a3fbf07296",
          "sha256": "f4b42246885fdfc30e2de8bedb389ce00bc0322d6925c376655697e60d502065",
          "sha1": "6551ad96f3a1ee13724c61603ffa1c499adf8df5",
          "md5": "3813eefa7ca0b2e295482e17bc403438"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-container-1.10.0-sources.jar",
          "url": "media3-container-1.10.0-sources.jar",
          "size": 48162,
          "sha512": "844da3c1fe0d01d8a7a0072fc276a08bb2b97de70b607299ca0e87ff1d595e60497dcef805e3bad22cf65b8735fe5424e1d044392603608b9882d2906461540b",
          "sha256": "12ce334607ba88b503fa68d43ba83bcd0cbaf896ddc5dd1d8f63e7c07f20279f",
          "sha1": "4245126918ddb18f81fa7143e11a7a27062b00a5",
          "md5": "69f1514330d127894112629b34fbdac7"
        }
      ]
    }
  ]
}
