{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui-leanback",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-ui-leanback-1.4.0.aar",
          "url": "media3-ui-leanback-1.4.0.aar",
          "size": 16296,
          "sha512": "7b9fc790d1870e747c24fcf32a4d4713e86c40e64bc8d45ae57ff71e61f1468cd5d5df5c4fc3427718b48cb032ec91b0ae0f76ae68e28a8f600476b5f81b37bf",
          "sha256": "2124700d424601f9c988baa8071cf1d6effb810b3da4d6ffd36ccd313b13e85d",
          "sha1": "6aeb34e3fd58b6d4bcb34aca9e29466543dd1781",
          "md5": "3966e8d5017b43fa0957da1d0c521d25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-leanback-1.4.0.aar",
          "url": "media3-ui-leanback-1.4.0.aar",
          "size": 16296,
          "sha512": "7b9fc790d1870e747c24fcf32a4d4713e86c40e64bc8d45ae57ff71e61f1468cd5d5df5c4fc3427718b48cb032ec91b0ae0f76ae68e28a8f600476b5f81b37bf",
          "sha256": "2124700d424601f9c988baa8071cf1d6effb810b3da4d6ffd36ccd313b13e85d",
          "sha1": "6aeb34e3fd58b6d4bcb34aca9e29466543dd1781",
          "md5": "3966e8d5017b43fa0957da1d0c521d25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-leanback-1.4.0-sources.jar",
          "url": "media3-ui-leanback-1.4.0-sources.jar",
          "size": 4407,
          "sha512": "20a816c372ac5e7835dbf83737469ea30354dd6b21d38d7164482fdbab04c9dbfa979ae2d9273f2c5449d39c331eb29e564a0d9226f660a9c17f6e12920f71b0",
          "sha256": "b48620ff7de85c0a7998d584cc30c0a365a5d94f218bc91c4f3f82db1c246276",
          "sha1": "8dd5e7d7535bc7ed58d9c8c102f5ca83e104e91f",
          "md5": "0861a5a93f2eb1dc600500acfe88e220"
        }
      ]
    }
  ]
}
