{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-alpha01.aar",
          "url": "media3-decode-av1-1.10.0-alpha01.aar",
          "size": 2178382,
          "sha512": "5f18d32b04636704d579bf4fab35f9d1caeeddd898b99589e60fd2d30b6ae4481d6b4f06a7dc7504063ec8d29c6aea75a00804b063a3198b76012cb3d26cf9af",
          "sha256": "10b205e3266abc761bed4657ded9fd922fa3fad5d85add72feb9bf678ad421ba",
          "sha1": "8ea905ecab6c92f24240c9b029f78ad58f384421",
          "md5": "691a5d9cfa1dec4f29471b551b6891f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-alpha01.aar",
          "url": "media3-decode-av1-1.10.0-alpha01.aar",
          "size": 2178382,
          "sha512": "5f18d32b04636704d579bf4fab35f9d1caeeddd898b99589e60fd2d30b6ae4481d6b4f06a7dc7504063ec8d29c6aea75a00804b063a3198b76012cb3d26cf9af",
          "sha256": "10b205e3266abc761bed4657ded9fd922fa3fad5d85add72feb9bf678ad421ba",
          "sha1": "8ea905ecab6c92f24240c9b029f78ad58f384421",
          "md5": "691a5d9cfa1dec4f29471b551b6891f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-alpha01-sources.jar",
          "url": "media3-decode-av1-1.10.0-alpha01-sources.jar",
          "size": 10338,
          "sha512": "53ba0e3a58acbb3d5e1c8766e58e0f72787fe6b1ab8371bfaa0bc81867269d7f573a4107f7cf576c07d00efe3fe4118de3654ae3526c5196f88d19e8dbbf2f0a",
          "sha256": "33284308e55d631071ec2834f84b195500a44fe7a6c9d13dd4d0f8ef11614e0c",
          "sha1": "df9b55fd0d6c081747562a24ba91e1711ffa94c2",
          "md5": "e9f6077c1100cd645389b9dfe841d5c0"
        }
      ]
    }
  ]
}
