{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-midi",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-midi-1.2.0.aar",
          "url": "media3-exoplayer-midi-1.2.0.aar",
          "size": 269734,
          "sha512": "4693aa058c62b78b77fb1ccad3bef7f6d5de0926baa38c24d506a8321bea8d0b54d0a543c82f117030c386e0d51ab5fb8bb83d85230b137201b5825d483ed815",
          "sha256": "ca200c0c82c701bf268483b68d57e7f142a9af3b140d58e66653bc158554222d",
          "sha1": "48a36372aa7223904135d99420e08e54ccb7c559",
          "md5": "1c3eebf1e4b0b3f97f7ea0213e18e92c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.philburk",
          "module": "jsyn",
          "version": {
            "requires": "40a41092cbab558d7d410ec43d93bb1e4121e86a"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-midi-1.2.0.aar",
          "url": "media3-exoplayer-midi-1.2.0.aar",
          "size": 269734,
          "sha512": "4693aa058c62b78b77fb1ccad3bef7f6d5de0926baa38c24d506a8321bea8d0b54d0a543c82f117030c386e0d51ab5fb8bb83d85230b137201b5825d483ed815",
          "sha256": "ca200c0c82c701bf268483b68d57e7f142a9af3b140d58e66653bc158554222d",
          "sha1": "48a36372aa7223904135d99420e08e54ccb7c559",
          "md5": "1c3eebf1e4b0b3f97f7ea0213e18e92c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-midi-1.2.0-sources.jar",
          "url": "media3-exoplayer-midi-1.2.0-sources.jar",
          "size": 35050,
          "sha512": "fc747bc1cdc168241dff11a477a5686ba88f8be5f8b02a2538f3ca74247565d0309ba34377f041beb56b050b5b0c7d1e7d072ed72fc6feb67a9b50783c5c061b",
          "sha256": "168fe4f7b58f6f458db45c618c8ecfd7c11e3c2023014d3a9fd2d7a6855b64cf",
          "sha1": "412c5fbafa9ecd81ef0ed1c86e83e4ab9fbdb10a",
          "md5": "04bf881e6ee1839b00cbb52f02ab741b"
        }
      ]
    }
  ]
}
