{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-vp9",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.10.0.aar",
          "url": "media3-decode-vp9-1.10.0.aar",
          "size": 9497,
          "sha512": "01781045159869611d3af5fa0a82d1382d0e89376926607fb42fa2a6f98805bbca34a994b01a15fd9e5cce6014deb7ef9d55b2bb99fe6acf0f35e44937063df5",
          "sha256": "bbdbefcc2f693d6ae519bdad7bd471a73d2c57f1a858ffe007369fc2b6f5d929",
          "sha1": "d1c91fb6659c3ecd88f1f256181beab9d18710f2",
          "md5": "d35137c227cb83228d939e18fdf9afb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.10.0.aar",
          "url": "media3-decode-vp9-1.10.0.aar",
          "size": 9497,
          "sha512": "01781045159869611d3af5fa0a82d1382d0e89376926607fb42fa2a6f98805bbca34a994b01a15fd9e5cce6014deb7ef9d55b2bb99fe6acf0f35e44937063df5",
          "sha256": "bbdbefcc2f693d6ae519bdad7bd471a73d2c57f1a858ffe007369fc2b6f5d929",
          "sha1": "d1c91fb6659c3ecd88f1f256181beab9d18710f2",
          "md5": "d35137c227cb83228d939e18fdf9afb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-vp9-1.10.0-sources.jar",
          "url": "media3-decode-vp9-1.10.0-sources.jar",
          "size": 8822,
          "sha512": "2594374f2ed77364c504b71343975dba4f6c2daee36f0e1dc60f62097c2fc433df8331a3c567165c5e42582ce331ac979f9ec9f7c0182d89f4be431fd28eeb8d",
          "sha256": "c9deea7e0fbbec2dc0f87e72de5b2147e6cf0bbdb20775d675cd114b13239ef9",
          "sha1": "145477e206abb0e68bbaf2bf4bf252e1b65a5908",
          "md5": "48373cf213bb108a2d150844b15fd69a"
        }
      ]
    }
  ]
}
