{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.6.0.aar",
          "url": "media3-decode-opus-1.6.0.aar",
          "size": 512364,
          "sha512": "25d845f2075f37e777035b5414082ef7b14b93186e781e7417913a69737b867beb99c50bbbf310977079059f00667079bd3a5cba0bd01779179f800c60872dc7",
          "sha256": "19a4137f7711af1e0652264fa9f9d796d30a46790229a15362e1e1dde0f81852",
          "sha1": "b6c0c17d410849e2ea0f983d5fe31959b66ca1df",
          "md5": "be2472326ad665f25f57b4fb6b7f268d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.6.0.aar",
          "url": "media3-decode-opus-1.6.0.aar",
          "size": 512364,
          "sha512": "25d845f2075f37e777035b5414082ef7b14b93186e781e7417913a69737b867beb99c50bbbf310977079059f00667079bd3a5cba0bd01779179f800c60872dc7",
          "sha256": "19a4137f7711af1e0652264fa9f9d796d30a46790229a15362e1e1dde0f81852",
          "sha1": "b6c0c17d410849e2ea0f983d5fe31959b66ca1df",
          "md5": "be2472326ad665f25f57b4fb6b7f268d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.6.0-sources.jar",
          "url": "media3-decode-opus-1.6.0-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
