{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-flac",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.10.1.aar",
          "url": "media3-decode-flac-1.10.1.aar",
          "size": 579709,
          "sha512": "cfaebe9461dfa34972872151cf792314812cad9a2771405e104850636aee48413ed38ee676893ba08c80763c0d549a87bc986fd2aa09dc2f5557abc1ab1c0e47",
          "sha256": "debc4812bee3f392282d519ed6e8110f8afe23e8d0e686408ae61571093b6935",
          "sha1": "859e8f350fe9dfbb9ee2f27df360c05e6774f532",
          "md5": "10c528c44b112c958db72c75ff52732a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.10.1.aar",
          "url": "media3-decode-flac-1.10.1.aar",
          "size": 579709,
          "sha512": "cfaebe9461dfa34972872151cf792314812cad9a2771405e104850636aee48413ed38ee676893ba08c80763c0d549a87bc986fd2aa09dc2f5557abc1ab1c0e47",
          "sha256": "debc4812bee3f392282d519ed6e8110f8afe23e8d0e686408ae61571093b6935",
          "sha1": "859e8f350fe9dfbb9ee2f27df360c05e6774f532",
          "md5": "10c528c44b112c958db72c75ff52732a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-flac-1.10.1-sources.jar",
          "url": "media3-decode-flac-1.10.1-sources.jar",
          "size": 15748,
          "sha512": "ace6d2a23a3ac31f89c72e99fa5e525e1dd02184583e2260ae39c102b8f3bbc891ae90e58e640e3e1a9bbc84511366521732ffe6edab21a47bb3ebc904e92e74",
          "sha256": "636547d168b74eb6dde49727aa1b5430eb79b5b86cc77808dd9aaa44dfa948dc",
          "sha1": "648f0d2d5ae45d632506a44abcc31d234c370b97",
          "md5": "26cc69a7600a7b8a9561233647815276"
        }
      ]
    }
  ]
}
