{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.11.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0-rc01.aar",
          "url": "media3-common-1.11.0-rc01.aar",
          "size": 643058,
          "sha512": "0eea30e7c94e26bca304e57a8d8c91af07f1ba33578fa9f59cb63b8fd9f3849edf3cee12d270c7f78f174da8dc6d9f6d47b9ad558fce646c227bb109795a04f1",
          "sha256": "02405f18709cfad15a8ce228504541062d4212cbfde79a3e76306b86588494fb",
          "sha1": "4c0ebdade0905a01a096fb7fa995122879601418",
          "md5": "a9f95f5422b2f59624abf21cf8c4fab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-ktor",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-av1",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-ffmpeg",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-flac",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-iamf",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-mpegh",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-opus",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-vp9",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect-lottie",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-effect-ndk",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector-frame",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.11.0-rc01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.11.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0-rc01.aar",
          "url": "media3-common-1.11.0-rc01.aar",
          "size": 643058,
          "sha512": "0eea30e7c94e26bca304e57a8d8c91af07f1ba33578fa9f59cb63b8fd9f3849edf3cee12d270c7f78f174da8dc6d9f6d47b9ad558fce646c227bb109795a04f1",
          "sha256": "02405f18709cfad15a8ce228504541062d4212cbfde79a3e76306b86588494fb",
          "sha1": "4c0ebdade0905a01a096fb7fa995122879601418",
          "md5": "a9f95f5422b2f59624abf21cf8c4fab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.11.0-rc01-sources.jar",
          "url": "media3-common-1.11.0-rc01-sources.jar",
          "size": 525444,
          "sha512": "a10ab048367d05dfbdff8f51b7a6387f2f4f63ab08070d828fdb6ba1b569f8279a260c18d7e3d801937b58a1df09137e3d58e252793c8f7503267b385c43abdc",
          "sha256": "be6ee74e87514e9a8d67c1609c4ff5d8c1cdce0fb4363fb4e4f5da077fb692e3",
          "sha1": "cb934a43c2f63ca72f04806193421c01dd8ccccc",
          "md5": "a66381bb2dc1698b9398f63389353b87"
        }
      ]
    }
  ]
}
