{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.6.1.aar",
          "url": "media3-extractor-1.6.1.aar",
          "size": 773606,
          "sha512": "4ffde1ee4a184430a3fcb9a92313c9f3f69bcfdb545554ba10b635f7d523d3843cde3e34088c37825a96bd524594adf401403eeabd7a3460f9abaae86daff200",
          "sha256": "107f6267a19a828438b0b840cf4c424b7200ac0e7b5a717d3584098098b17116",
          "sha1": "1b8dea47cf78d3447f10f69b1e81018cd7f945f8",
          "md5": "bf291e30bc5a19fa859b45160f2d0e20"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.6.1.aar",
          "url": "media3-extractor-1.6.1.aar",
          "size": 773606,
          "sha512": "4ffde1ee4a184430a3fcb9a92313c9f3f69bcfdb545554ba10b635f7d523d3843cde3e34088c37825a96bd524594adf401403eeabd7a3460f9abaae86daff200",
          "sha256": "107f6267a19a828438b0b840cf4c424b7200ac0e7b5a717d3584098098b17116",
          "sha1": "1b8dea47cf78d3447f10f69b1e81018cd7f945f8",
          "md5": "bf291e30bc5a19fa859b45160f2d0e20"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.6.1-sources.jar",
          "url": "media3-extractor-1.6.1-sources.jar",
          "size": 668572,
          "sha512": "8ce83a25cafc212d881a5d22b7d56501e719c9097e5dde7620552db863d3c65b634e556afe365fee804adbd4f803c8eefe8c94c210122398be5b838799327f10",
          "sha256": "8453813e8c64eaec0374aceacd0810c4cf7c3b2019961f2fee3609c4c4b0e3e1",
          "sha1": "168f5c757bc7dadf6d627cc56dac6b58ffbef729",
          "md5": "4a526c529793a2e77b6ae65a17c649e3"
        }
      ]
    }
  ]
}
