{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-1.10.0.aar",
          "url": "media3-decoder-1.10.0.aar",
          "size": 18220,
          "sha512": "fe11d3a51376b3a8f75e030be2e955629c81e9f78aef255372bdd97fcc94b3ddcf3dd79811bd6bb2bb1f92da8f5084a9474630fde9d3b28b206744a18924af61",
          "sha256": "a432e2e91411d8b6e9445d230d1eaef3a7d68846e0c40c26e856a87abab6344d",
          "sha1": "ec972fa09a8549b479922fa984e31c37e756094b",
          "md5": "93b79d3152cf5967d9ec32f9e2beecb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-1.10.0.aar",
          "url": "media3-decoder-1.10.0.aar",
          "size": 18220,
          "sha512": "fe11d3a51376b3a8f75e030be2e955629c81e9f78aef255372bdd97fcc94b3ddcf3dd79811bd6bb2bb1f92da8f5084a9474630fde9d3b28b206744a18924af61",
          "sha256": "a432e2e91411d8b6e9445d230d1eaef3a7d68846e0c40c26e856a87abab6344d",
          "sha1": "ec972fa09a8549b479922fa984e31c37e756094b",
          "md5": "93b79d3152cf5967d9ec32f9e2beecb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-1.10.0-sources.jar",
          "url": "media3-decoder-1.10.0-sources.jar",
          "size": 19062,
          "sha512": "3a4cacf4bd7c19a8f6de4209c2deb23ca91ba3ae69e63add3d80b7877afc9c701cb6ad139be5ff8d18c15919d8695322305cff3ea13309708c6b7667dde8ebee",
          "sha256": "ebb3aa11a3b08532a76123e74931d28f6674013988a5f7bc56bec91a561b3c85",
          "sha1": "329cfc71711f95a737926557b5b21866142c9319",
          "md5": "37f7ae0c35886a40b9fd053c643432ca"
        }
      ]
    }
  ]
}
